/**
 * KHUNG CÂU HỎI v3 — sinh tự động từ KHUNG-LUAN-GIAI-v3.xlsx (sheet 1, 2, 3) mà
 * chủ dự án đã duyệt ngày 23/09/2026. Đừng sửa câu chữ ở đây bằng tay: sửa trong
 * khung rồi sinh lại, không thì hai bản lệch nhau mà không ai biết bản nào đúng.
 *
 * Token cung đặc biệt: "THAN" = cung an Thân, "DV" = cung đại vận đang chạy,
 * "TH" = cung tiểu hạn của năm xem.
 */

export type LopVan = 'dv' | 'chuoi' | 'th' | 'th3' | 'nguyet' | 'diem';

export interface ChuDeV3 {
  ma: string;
  id: string;
  ten: string;
  cungChinh: string;
  phuTro: { cung: string; vaiTro: string }[];
  saoToanCuc: string;
}

export interface CauHoiV3 {
  id: string;
  loai: 'tong-quan' | 'chuyen-sau';
  chuDe: string;
  cauHoi: string;
  nhanDuoc: string;
  /** Những ý bài phải có — lấy từ cột "Ý bắt buộc phải có" / "Cung & yếu tố" */
  yBatBuoc: string;
  /** Cung phải đọc, theo thứ tự ưu tiên. Rỗng = cung chính của chủ đề + tam phương */
  cung: string[];
  yeuToThem: string;
  van: LopVan[];
  khongDuoc: string;
}

export const PHIEN_BAN_KHUNG_V3 = '2026.09.3';

export const CHU_DE_V3: ChuDeV3[] = [
  { ma: "TC", id: "tinh-cach", ten: "Tính cách & con người", cungChinh: "Mệnh", phuTro: [{"cung": "Thân", "vaiTro": "con người từ khoảng 30 tuổi trở đi; nặng dần theo tuổi"}, {"cung": "Tật Ách", "vaiTro": "\"mệnh thứ hai\": nét tính cách ẩn, bản năng, phản ứng khi áp lực, thể chất"}, {"cung": "Phúc Đức", "vaiTro": "tư tưởng, đời sống tinh thần, cách hưởng thụ"}], saoToanCuc: "Chính tinh tại Mệnh + độ sáng; cách cục của tam phương Mệnh; Mệnh chủ, Thân chủ; ngũ hành bản mệnh – Cục; vòng Tràng Sinh tại Mệnh; Tuần/Triệt tại Mệnh" },
  { ma: "SN", id: "su-nghiep", ten: "Sự nghiệp", cungChinh: "Quan Lộc", phuTro: [{"cung": "Thiên Di", "vaiTro": "môi trường bên ngoài, cơ hội nơi xa"}, {"cung": "Nô Bộc", "vaiTro": "đồng nghiệp, cấp dưới, khách hàng"}, {"cung": "Phụ Mẫu", "vaiTro": "cấp trên, cơ quan nhà nước, giấy tờ, học vấn"}, {"cung": "Điền Trạch", "vaiTro": "nơi làm việc, cơ sở kinh doanh"}], saoToanCuc: "Hóa Quyền, Hóa Khoa; Khôi Việt, Tả Hữu; Xương Khúc; Thiên Mã; Quốc Ấn, Thai Phụ, Phong Cáo; Lộc Tồn" },
  { ma: "TB", id: "tien-bac", ten: "Tiền bạc", cungChinh: "Tài Bạch", phuTro: [{"cung": "Điền Trạch", "vaiTro": "kho của: giữ tiền, tài sản, bất động sản"}, {"cung": "Thiên Di", "vaiTro": "tiền từ bên ngoài, nơi xa"}, {"cung": "Nô Bộc", "vaiTro": "tiền qua người khác: khách hàng, cấp dưới"}, {"cung": "Huynh Đệ", "vaiTro": "hùn vốn, vay mượn người thân"}, {"cung": "Phu Thê", "vaiTro": "bạn đời tác động tới tiền"}, {"cung": "Tử Tức", "vaiTro": "hợp tác, đầu tư [theo một số trường phái — cần kiểm]"}], saoToanCuc: "Lộc Tồn, Hóa Lộc (vị trí trên cả lá); Địa Không, Địa Kiếp; Đại Hao, Tiểu Hao; Hóa Kỵ; Hỏa Tinh, Linh Tinh (tiền đột phát)" },
  { ma: "TD", id: "tinh-duyen", ten: "Tình duyên & hôn nhân", cungChinh: "Phu Thê", phuTro: [{"cung": "Mệnh / Thân", "vaiTro": "bản thân mình trong hôn nhân"}, {"cung": "Tử Tức", "vaiTro": "đời sống vợ chồng, chuyện chăn gối"}, {"cung": "Điền Trạch", "vaiTro": "tổ ấm, đời sống chung"}], saoToanCuc: "Sao đào hoa trên cả lá: Đào Hoa, Hồng Loan, Thiên Hỷ, Thiên Riêu, Hàm Trì, Mộc Dục; Cô Thần, Quả Tú; Tuần/Triệt tại Phu Thê" },
  { ma: "CC", id: "con-cai", ten: "Con cái", cungChinh: "Tử Tức", phuTro: [{"cung": "Phu Thê", "vaiTro": "vợ chồng ảnh hưởng tới con"}, {"cung": "Phúc Đức", "vaiTro": "phúc để lại cho con"}, {"cung": "Mệnh", "vaiTro": "cách mình làm cha mẹ"}], saoToanCuc: "Thai, Dưỡng (vòng Tràng Sinh); sát tinh và Tuần/Triệt tại Tử Tức — KHÔNG luận số con, giới tính" },
  { ma: "GD", id: "gia-dinh", ten: "Cha mẹ & gia đình gốc", cungChinh: "Phụ Mẫu", phuTro: [{"cung": "Phúc Đức", "vaiTro": "dòng họ, tổ tiên"}, {"cung": "Mệnh", "vaiTro": "mình trong mắt cha mẹ"}, {"cung": "Thái Dương / Thái Âm", "vaiTro": "vị trí và độ sáng: cha / mẹ (bất kể nằm ở cung nào)"}], saoToanCuc: "Âm Dương thuận lý hay nghịch lý; Hóa Khoa; Ân Quang, Thiên Quý; Tang Môn, Bạch Hổ, Điếu Khách" },
  { ma: "AE", id: "anh-em", ten: "Anh chị em", cungChinh: "Huynh Đệ", phuTro: [{"cung": "Nô Bộc", "vaiTro": "đối cung: người ngoài so với người nhà"}], saoToanCuc: "Sát tinh, Không Kiếp tại Huynh Đệ; cung không có chính tinh thì mượn chính tinh của Nô Bộc" },
  { ma: "QN", id: "quy-nhan", ten: "Bạn bè, cộng sự, quý nhân", cungChinh: "Nô Bộc", phuTro: [{"cung": "Thiên Di", "vaiTro": "người gặp ngoài xã hội"}, {"cung": "Phụ Mẫu", "vaiTro": "người trên nâng đỡ"}], saoToanCuc: "Quý nhân tinh trên cả lá: Khôi Việt, Tả Hữu, Thiên Quan, Thiên Phúc, Ân Quang, Thiên Quý, Hóa Khoa" },
  { ma: "PD", id: "phuc-duc", ten: "Phúc đức & đời sống tinh thần", cungChinh: "Phúc Đức", phuTro: [{"cung": "Phụ Mẫu", "vaiTro": "cha mẹ, bề trên"}, {"cung": "Điền Trạch", "vaiTro": "tổ nghiệp"}, {"cung": "Mệnh", "vaiTro": "phần mình tự tạo"}], saoToanCuc: "Thiên Đức, Nguyệt Đức, Long Đức, Phúc Đức (vòng Thái Tuế); Thiên Quan, Thiên Phúc; Hóa Lộc/Hóa Kỵ tại Phúc Đức" },
  { ma: "SK", id: "suc-khoe", ten: "Sức khỏe", cungChinh: "Tật Ách", phuTro: [{"cung": "Mệnh / Thân", "vaiTro": "thể chất gốc"}, {"cung": "Phúc Đức", "vaiTro": "sức bền, tinh thần"}, {"cung": "Ngũ hành bản mệnh – Cục", "vaiTro": "nền thể trạng"}], saoToanCuc: "Kình Dương, Đà La, Hỏa Tinh, Linh Tinh, Địa Không, Địa Kiếp; Hóa Kỵ; Thiên Hình; Bệnh Phù — chỉ luận XU HƯỚNG, không chẩn đoán" },
  { ma: "NC", id: "nha-cua", ten: "Nhà cửa & tài sản", cungChinh: "Điền Trạch", phuTro: [{"cung": "Tài Bạch", "vaiTro": "sức tài chính để mua, giữ"}, {"cung": "Phụ Mẫu", "vaiTro": "thừa kế"}, {"cung": "Thiên Di", "vaiTro": "chuyển chỗ ở, nơi xa"}], saoToanCuc: "Lộc Tồn, Hóa Lộc, Đường Phù; Địa Không, Địa Kiếp, Đại Hao; Hóa Kỵ (giấy tờ, tranh chấp)" },
  { ma: "RN", id: "ra-ngoai", ten: "Ra ngoài, đi xa, môi trường", cungChinh: "Thiên Di", phuTro: [{"cung": "Mệnh", "vaiTro": "đối chiếu: mình ở nhà và mình ở ngoài"}], saoToanCuc: "Thiên Mã, Lộc Tồn (Lộc Mã); Tả Hữu, Khôi Việt; sát tinh; Lưu Hà, Thiên Hình (an toàn đi lại)" },
  { ma: "HV", id: "hoc-van", ten: "Học vấn & bằng cấp", cungChinh: "Quan Lộc", phuTro: [{"cung": "Phụ Mẫu", "vaiTro": "văn thư, thi cử, thầy"}, {"cung": "Mệnh", "vaiTro": "tư chất học"}], saoToanCuc: "Văn Xương, Văn Khúc, Khôi Việt, Hóa Khoa, Long Trì, Phượng Các, Tấu Thư, Bác Sĩ, LN Văn Tinh" },
  { ma: "VH", id: "van-han", ten: "Vận hạn", cungChinh: "Cung đại vận / tiểu hạn", phuTro: [{"cung": "Nguyên cục", "vaiTro": "vận chỉ kích hoạt cái vốn có; luôn đối chiếu với cung gốc cùng chủ đề"}], saoToanCuc: "Tam phương tứ chính của cung vận; lưu Thái Tuế; lưu tứ hóa theo can năm; lưu Lộc Tồn, lưu Kình Đà; nguyệt hạn (tùy chọn)" },
];

export const CAU_HOI_V3: CauHoiV3[] = [
  { id: "TQ01", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Tôi là người như thế nào?", nhanDuoc: "Một câu định danh + một câu về mặt bên trong", yBatBuoc: "Mệnh (chính) + tam hợp Tài Bạch, Quan Lộc + xung Thiên Di; Thân; Tật Ách, Phúc Đức cho mặt bên trong", cung: ["Mệnh", "THAN", "Tật Ách", "Phúc Đức"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "TQ02", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Điểm mạnh nổi bật nhất của tôi?", nhanDuoc: "Một năng lực + một lợi thế trong đời", yBatBuoc: "Cách cục cát mạnh nhất; cung có chính tinh miếu vượng + cát tinh; vị trí Hóa Lộc / Quyền / Khoa", cung: ["Mệnh", "Quan Lộc", "Tài Bạch"], yeuToThem: "", van: ["diem"], khongDuoc: "" },
  { id: "TQ03", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Điều tôi cần lưu ý nhất?", nhanDuoc: "Một kiểu sai lặp lại hoặc một mặt yếu của đời", yBatBuoc: "Cung yếu nhất (chính tinh hãm + sát tinh + Hóa Kỵ); sát tinh ở Mệnh, Thân, Phúc Đức", cung: ["Mệnh", "Phúc Đức"], yeuToThem: "", van: ["diem"], khongDuoc: "" },
  { id: "TQ04", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Lá số mạnh ở mặt nào, yếu ở mặt nào?", nhanDuoc: "Xếp 12 mặt đời vào 3 nhóm Thuận lợi / Ổn định / Cần chăm chút", yBatBuoc: "Chấm từng cung theo luật: chính tinh + độ sáng + cát/sát tinh + tứ hóa + Tuần/Triệt (engine chấm, không dùng LLM)", cung: ["Mệnh"], yeuToThem: "", van: ["diem"], khongDuoc: "" },
  { id: "TQ05", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Tôi hợp hướng nghề nào?", nhanDuoc: "Một dòng: nhóm nghề + vai trò", yBatBuoc: "Quan Lộc + tam phương", cung: ["Quan Lộc"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "TQ06", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Tiền bạc của tôi nói chung thế nào?", nhanDuoc: "Mức kiếm / mức giữ + nguồn chính", yBatBuoc: "Tài Bạch + tam phương + Phúc Đức (xung) + Điền Trạch", cung: ["Tài Bạch", "Phúc Đức", "Điền Trạch"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "TQ07", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Tình duyên của tôi nói chung thế nào?", nhanDuoc: "Kiểu duyên + sớm hay muộn", yBatBuoc: "Phu Thê + tam phương", cung: ["Phu Thê"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "TQ08", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Giai đoạn 10 năm hiện tại của tôi là giai đoạn gì?", nhanDuoc: "Tên giai đoạn + chủ đề + 1 lưu ý", yBatBuoc: "Cung đại vận hiện tại + tam phương, đặt lên nguyên cục", cung: ["DV"], yeuToThem: "", van: ["dv"], khongDuoc: "" },
  { id: "TQ09", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Năm nay tôi cần biết gì?", nhanDuoc: "Chủ đề năm + nên / tránh", yBatBuoc: "Tiểu hạn + lưu Thái Tuế + lưu tứ hóa + đại vận", cung: ["TH"], yeuToThem: "", van: ["th", "dv"], khongDuoc: "" },
  { id: "TQ10", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Đường đời của tôi đi lên thế nào (tiền vận – trung vận – hậu vận)?", nhanDuoc: "Mỗi giai đoạn 10 năm 1 dòng", yBatBuoc: "Tất cả cung đại vận; Mệnh (tiền vận) vs Thân (hậu vận); Triệt (tiền vận), Tuần (hậu vận)", cung: ["Mệnh", "THAN"], yeuToThem: "", van: ["chuoi"], khongDuoc: "" },
  { id: "TQ11", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Tôi nên xem sâu phần nào trước?", nhanDuoc: "2–3 chủ đề + lý do 1 dòng (sinh theo luật, không phải luận giải)", yBatBuoc: "Điểm mạnh / yếu (TQ04) + đại vận hiện tại + độ nổi bật", cung: ["Mệnh"], yeuToThem: "", van: ["diem", "dv", "chuoi"], khongDuoc: "" },
  // tinh-cach — viết lại 26/09/2026 theo luồng chủ dự án (Pain point → Narrative → Prediction)
  { id: "TC01", loai: "chuyen-sau", chuDe: "tinh-cach", cauHoi: "Bản chất sâu nhất trong con người tôi là gì?", nhanDuoc: "MỘT trục chính của khí chất (kiểm soát / tự do / thành tựu / tình cảm / an toàn / ảnh hưởng), điều coi trọng nhất, và bên ngoài – bên trong có vênh nhau không", yBatBuoc: "Trục chính + Biểu hiện + Phần gốc ít đổi theo tuổi", cung: [], yeuToThem: "Chính tinh Mệnh + độ sáng; cách cục; phụ tinh tại Mệnh; Mệnh không có chính tinh thì mượn Thiên Di", van: [], khongDuoc: "Không liệt kê hàng loạt tính từ; phải tìm ra một trục chính" },
  { id: "TC02", loai: "chuyen-sau", chuDe: "tinh-cach", cauHoi: "Điều gì ở tôi nổi bật hơn phần đông người khác?", nhanDuoc: "Năng lực tự nhiên, điều người khác thường tin cậy mình, nó tạo lợi thế ở đâu và mạnh lên hay yếu đi khi trưởng thành", yBatBuoc: "Đáp + Vận hành trong đời + Khi nào mạnh lên", cung: [], yeuToThem: "Cát tinh trong tam phương Mệnh: Tả Hữu, Khôi Việt, Xương Khúc, Lộc Tồn, Hóa Lộc/Quyền/Khoa", van: [], khongDuoc: "Không dùng ngôn ngữ CV (\"có khả năng lãnh đạo, giao tiếp tốt\")" },
  { id: "TC03", loai: "chuyen-sau", chuDe: "tinh-cach", cauHoi: "Điểm nào trong tính cách dễ khiến tôi tự làm khó mình nhất?", nhanDuoc: "Điểm mù, thói quen dễ lặp, lúc điểm mạnh thành điểm yếu, dễ trả giá ở mặt nào (tình cảm, tiền, công việc, quan hệ), nhận ra sớm hay muộn", yBatBuoc: "Đáp + Nó dễ khiến loại chuyện gì xảy ra", cung: ["Mệnh", "Tật Ách", "Phúc Đức"], yeuToThem: "Sát tinh (Kình, Đà, Hỏa, Linh, Không, Kiếp), Hóa Kỵ, chính tinh hãm", van: [], khongDuoc: "Không dọa, không gắn nhãn xấu" },
  { id: "TC04", loai: "chuyen-sau", chuDe: "tinh-cach", cauHoi: "Khi gặp áp lực hoặc biến cố, tôi dễ trở thành phiên bản nào của mình?", nhanDuoc: "Phản ứng khi mất kiểm soát (thu mình, nóng lên, cắt đứt, kiểm soát người khác hay cố tự gánh), giữ tổn thương lâu hay phản ứng ngay, biến cố làm mạnh lên hay mất phương hướng", yBatBuoc: "Đáp + Biểu hiện", cung: ["Tật Ách", "Phúc Đức", "Mệnh"], yeuToThem: "Tật Ách = mệnh thứ hai (bản năng); Phúc Đức = tinh thần; so với Mệnh để chỉ ra độ vênh", van: ["dv"], khongDuoc: "Không chuyển sang lời khuyên quản lý căng thẳng" },
  { id: "TC05", loai: "chuyen-sau", chuDe: "tinh-cach", cauHoi: "Người khác nhìn tôi có giống con người thật của tôi không?", nhanDuoc: "Ấn tượng đầu, hình ảnh xã hội, người khác dễ hiểu sai điều gì, vì sao đôi khi tạo khoảng cách, kiểu người nào thường nhìn ra con người thật", yBatBuoc: "Đáp + Hiểu lầm hay gặp", cung: ["Thiên Di", "Mệnh"], yeuToThem: "Chính tinh Thiên Di; Tả Hữu, Khôi Việt; sát tinh ở Thiên Di", van: [], khongDuoc: "" },
  { id: "TC06", loai: "chuyen-sau", chuDe: "tinh-cach", cauHoi: "Tôi dễ đưa ra những quyết định sai ở đâu?", nhanDuoc: "Nhanh hay chậm, quá tin mình hay quá nghe người, mặt đời dễ quyết sai hơn, sai vì nóng vội / do dự / cảm xúc / tham vọng", yBatBuoc: "Đáp + Mặt đời dễ quyết sai", cung: ["Mệnh", "Quan Lộc", "Tài Bạch"], yeuToThem: "Hóa Kỵ, Hóa Quyền; Thiên Cơ, Cự Môn (suy tính); Thất Sát, Phá Quân (quyết nhanh)", van: [], khongDuoc: "" },
  { id: "TC07", loai: "chuyen-sau", chuDe: "tinh-cach", cauHoi: "Càng lớn tuổi, tôi sẽ thay đổi thành người như thế nào?", nhanDuoc: "Tính cách tuổi trẻ → điều đổi ở trung vận → điều ngày càng rõ, điều mềm đi → phiên bản hậu vận", yBatBuoc: "Đáp theo dòng thời gian", cung: ["Mệnh", "THAN"], yeuToThem: "Cung Thân (nặng dần sau khoảng 30); Tuần (hậu vận) / Triệt (tiền vận) tại Mệnh, Thân", van: ["chuoi"], khongDuoc: "" },
  // SỰ NGHIỆP viết lại 25/09/2026 theo review của chủ dự án: tám câu là tám LÁT CẮT nối thành một đường đọc
  // (tạo giá trị → vị trí → nghề → mô hình → nút thắt → người nâng/cản → đường lên & đỉnh → đang ở đâu), thay vì
  // tám bản chiếu lại cùng một kết luận. Bỏ "môi trường" (gộp vào SN02) và "xa quê" (trùng RN02 của chủ đề Đi xa).
  { id: "SN01", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Trong công việc, tôi tạo ra giá trị tốt nhất bằng cách nào?", nhanDuoc: "Cách tạo giá trị cốt lõi — giải quyết vấn đề, dẫn dắt, vận hành, kết nối, phân tích, kiểm soát, xây hệ thống, sáng tạo… — và nó hiện ra thế nào trong một ngày làm việc. CHƯA nói tên nghề", yBatBuoc: "Đáp (một cách tạo giá trị chính) + Biểu hiện + Khi nào mạnh lên", cung: ["Quan Lộc", "Mệnh"], yeuToThem: "Tử Vi, Thiên Phủ, Thiên Tướng (tổ chức, quản lý); Thất Sát, Phá Quân (tiên phong); Cơ Nguyệt Đồng Lương (chuyên môn, hỗ trợ); Cự Môn (dùng lời nói); Tham Lang (giao tế); Hóa Quyền", van: [], khongDuoc: "Không nêu tên ngành nghề — phần đó ở câu nhóm nghề" },
  { id: "SN02", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Tôi hợp đứng ở vị trí nào trong một tổ chức?", nhanDuoc: "Chuyên gia / cố vấn / quản lý / người dẫn dắt / người vận hành / người tự lập — một vị trí chính + một vị trí phụ; cần nhiều hay ít quyền quyết định; kiểu tổ chức làm vị trí ấy phát huy", yBatBuoc: "Đáp + Vì sao + Kiểu tổ chức hợp", cung: ["Quan Lộc", "Mệnh", "Phụ Mẫu"], yeuToThem: "Phụ Mẫu tốt → hợp tổ chức có cấp trên rõ; Thiên Di mạnh → hợp môi trường ngoài; Tử Phủ Vũ Tướng (điều hành); Cơ Nguyệt Đồng Lương (tham mưu)", van: [], khongDuoc: "" },
  { id: "SN03", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Những nhóm nghề, lĩnh vực nào có thể đưa tôi đi xa?", nhanDuoc: "Bản chất công việc hợp TRƯỚC (vài đặc tính), rồi 3–5 nhóm ngành làm ví dụ nơi đặc tính ấy xuất hiện, và 1–2 nhóm ít hợp", yBatBuoc: "Đặc tính công việc → Nhóm ngành ví dụ → Ít hợp", cung: [], yeuToThem: "Bảng tri thức sao → nghề (chờ chuyên gia duyệt); Xương Khúc (chữ nghĩa), Vũ Khúc (tài chính), Thiên Mã (di chuyển), Hóa Quyền; ngũ hành Mệnh chỉ để tham khảo", van: [], khongDuoc: "Không mở bài bằng tên ngành; không nói \"hợp nhất với ngành X\" như định danh — người đang làm nghề khác cũng phải thấy mình trong đó" },
  { id: "SN04", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Tôi hợp làm công, làm tự do hay tự xây một sự nghiệp riêng?", nhanDuoc: "Mô hình hợp nhất + mô hình thứ hai + khi nào tự làm chủ tốt hơn + làm chủ quá sớm dễ vướng gì", yBatBuoc: "Đáp có điều kiện + Khi nào", cung: ["Quan Lộc", "Tài Bạch", "Mệnh", "Nô Bộc", "Huynh Đệ", "Thiên Di"], yeuToThem: "Nô Bộc (khách, cấp dưới), Huynh Đệ (hùn), Thiên Di (thị trường ngoài)", van: ["chuoi"], khongDuoc: "Không khẳng định chắc chắn thành hay bại" },
  { id: "SN05", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Điều gì dễ trở thành nút thắt lớn nhất trong sự nghiệp của tôi?", nhanDuoc: "MỘT nút thắt chính (thiếu quyền, chọn sai môi trường, cấp trên, đổi việc, thiếu kiên nhẫn, sai đối tác, tự ái…) + nó thường xảy ra thế nào + dấu hiệu nhận ra sớm", yBatBuoc: "Đáp + Biểu hiện + Dấu hiệu", cung: ["Quan Lộc", "Mệnh", "Thiên Di"], yeuToThem: "Sát tinh, Hóa Kỵ, Tuần/Triệt trên tam phương Quan Lộc; Không Kiếp", van: [], khongDuoc: "" },
  { id: "SN06", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Trong công việc, tôi dễ gặp quý nhân hay đối thủ?", nhanDuoc: "Ai thường nâng (cấp trên / cộng sự / khách hàng), ai dễ cản, cạnh tranh công khai hay ngầm", yBatBuoc: "Người nâng / Người cản / Kiểu va chạm", cung: ["Phụ Mẫu", "Huynh Đệ", "Nô Bộc"], yeuToThem: "Phụ Mẫu = cấp trên; Huynh Đệ = ngang hàng; Nô Bộc = cấp dưới, khách; Khôi Việt, Tả Hữu, Thiên Quan, Thiên Phúc (quý nhân); Kình Đà, Hóa Kỵ (va chạm)", van: [], khongDuoc: "" },
  { id: "SN07", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Sự nghiệp của tôi thường đi lên theo kiểu nào, đỉnh ở đâu?", nhanDuoc: "Kiểu đi lên (chậm chắc / bật nhanh / vài lần chuyển hướng / chuyên môn rồi quản lý / làm công rồi tự làm) + đỉnh của CÁI GÌ (chức vụ, quyền, tiền, danh tiếng) ở giai đoạn nào + giai đoạn trước đỉnh là tích lũy hay trắc trở", yBatBuoc: "Kiểu đi lên + Đỉnh của gì, khi nào + Vì sao", cung: [], yeuToThem: "Hóa Quyền, Khôi Việt, Quốc Ấn, Thai Phụ, Phong Cáo", van: ["chuoi"], khongDuoc: "Không nêu chức danh cụ thể như sự thật; không phán đỉnh tuyệt đối" },
  { id: "SN08", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Tôi đang ở đâu trên con đường sự nghiệp ấy?", nhanDuoc: "Chặng hiện tại (tích lũy / chuẩn bị đổi / sắp mở cơ hội / nên đi sâu / bước sang quản lý) + năm nay nghiêng về điều gì + điều kiện để chặng này thành bước tiến", yBatBuoc: "Đáp + Điều kiện", cung: ["DV", "Quan Lộc"], yeuToThem: "Tam phương cung vận; tiểu hạn năm nay; lưu tứ hóa", van: ["dv", "th"], khongDuoc: "" },
  // tien-bac — viết lại 26/09/2026 theo luồng chủ dự án (Pain point → Narrative → Prediction)
  { id: "TB01", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Nhìn tổng thể, đường tiền bạc của tôi thuộc kiểu nào?", nhanDuoc: "Kiếm dễ hay qua nhiều bước, đều hay từng đợt, sớm hay muộn, tự thân hay có trợ lực, ổn định hay biến động", yBatBuoc: "Đáp + Mức (engine chấm) + Kiểu", cung: [], yeuToThem: "Luật chấm Tài Bạch; Tuần/Triệt tại Tài Bạch (mốc tiền vận – hậu vận)", van: [], khongDuoc: "Mức do engine chấm, không để model tự chấm" },
  { id: "TB02", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Tiền lớn của tôi thường đến từ đâu?", nhanDuoc: "Phân biệt nguồn thu thường xuyên với nguồn có thể tạo bước nhảy (nghề, kinh doanh, quản lý, đầu tư, tài sản, quan hệ, hôn nhân, thừa hưởng)", yBatBuoc: "Nguồn thường xuyên + Nguồn tạo bước nhảy", cung: [], yeuToThem: "Vị trí Lộc Tồn, Hóa Lộc trên cả lá; chính tinh Tài Bạch; Nô Bộc, Phu Thê, Điền Trạch", van: [], khongDuoc: "Không hứa số tiền" },
  { id: "TB03", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Tôi kiếm được tiền rồi có giữ được không?", nhanDuoc: "Khả năng tích lũy, tiền hay hao vào đâu, hao chủ động hay bất ngờ, có kiểu kiếm tốt mà khó tích không", yBatBuoc: "Đáp + Chỗ hao chính", cung: ["Tài Bạch", "Phúc Đức", "Điền Trạch"], yeuToThem: "Không Kiếp, Đại Hao, Tiểu Hao, Phá Quân, Hóa Kỵ; Lộc Tồn (giữ của)", van: [], khongDuoc: "" },
  { id: "TB04", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Tôi có dễ mất tiền vì quyết định sai hoặc vì người khác không?", nhanDuoc: "MỘT nguồn hao tài nổi bật nhất: đầu tư sai, cho vay, hùn vốn, người thân, bạn bè, bạn đời, đối tác hay quyết định nóng vội", yBatBuoc: "Nguồn hao chính + Tình huống dễ xảy ra", cung: ["Tài Bạch", "Huynh Đệ", "Nô Bộc", "Phu Thê"], yeuToThem: "Sát tinh, Không Kiếp, Hóa Kỵ ở Huynh Đệ, Nô Bộc; Tử Tức [một số trường phái xem là cung hợp tác]", van: [], khongDuoc: "" },
  { id: "TB05", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Tôi có duyên đầu tư và tạo tài sản không?", nhanDuoc: "Tích sản hay đầu cơ, dài hạn hay ngắn hạn, kênh tài chính / nhà đất / kinh doanh, có dễ gặp một lần mất lớn, thành nhờ kỹ năng hay thời vận", yBatBuoc: "Đáp có điều kiện + Kiểu hợp", cung: ["Tài Bạch", "Điền Trạch", "Phúc Đức", "Mệnh"], yeuToThem: "Thiên Phủ, Vũ Khúc (tích sản) vs Tham Lang, Phá Quân (mạo hiểm); Không Kiếp, Hỏa Linh (đột phát – đột mất)", van: ["dv"], khongDuoc: "Không tư vấn mua tài sản cụ thể" },
  { id: "TB06", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Đường tài chính của tôi thay đổi thế nào theo tuổi?", nhanDuoc: "Thời kỳ khó kiếm, thời kỳ thu nhập tăng, thời kỳ biến động, giai đoạn tích tài sản, giai đoạn dễ tạo bước nhảy", yBatBuoc: "Dòng thời gian + Bước nhảy", cung: ["Tài Bạch", "Điền Trạch"], yeuToThem: "Đại vận có Lộc hoặc đi qua Tài Bạch, Điền Trạch; đại vận gặp Không Kiếp, Hóa Kỵ", van: ["chuoi"], khongDuoc: "" },
  { id: "TB07", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Cuối cùng, tôi có khả năng tạo được mức sống và tài sản thế nào?", nhanDuoc: "Trả lời thẳng \"có giàu không\" với sắc thái: khá giả / tích sản tốt / giàu muộn / biến động mạnh; giàu nhờ thu nhập hay tài sản; hậu vận tài chính; điều kiện quan trọng nhất", yBatBuoc: "Đáp thẳng + Điều kiện", cung: ["THAN", "Điền Trạch", "Tài Bạch"], yeuToThem: "Cung Thân; đại vận sau 50; Tuần tại Tài Bạch hoặc Điền Trạch", van: ["chuoi"], khongDuoc: "Không hứa số tiền" },
  // tinh-duyen — viết lại 26/09/2026 theo luồng chủ dự án (Pain point → Narrative → Prediction)
  { id: "TD01", loai: "chuyen-sau", chuDe: "tinh-duyen", cauHoi: "Đường tình cảm của tôi nhìn chung thuộc kiểu nào?", nhanDuoc: "Sớm hay muộn, nhiều hay ít mối, sâu hay biến động, tình cảm ảnh hưởng đời mạnh hay nhẹ", yBatBuoc: "Đáp + Kiểu", cung: [], yeuToThem: "Chính tinh, phụ tinh tại Phu Thê; Tuần/Triệt tại Phu Thê; sao đào hoa trên cả lá", van: [], khongDuoc: "" },
  { id: "TD02", loai: "chuyen-sau", chuDe: "tinh-duyen", cauHoi: "Khi yêu, tôi thường yêu theo kiểu nào?", nhanDuoc: "Chủ động hay bị động, sâu hay nông, chiếm hữu, lý trí, dễ hy sinh, dễ rút lui — kiểu này dẫn tới chuyện gì", yBatBuoc: "Đáp + Hệ quả", cung: ["Mệnh", "Phu Thê", "Phúc Đức"], yeuToThem: "Sao đào hoa tại Mệnh, Phúc Đức; Tham Lang, Liêm Trinh", van: [], khongDuoc: "" },
  { id: "TD03", loai: "chuyen-sau", chuDe: "tinh-duyen", cauHoi: "Tôi hay bị thu hút bởi kiểu người nào — và đó có phải người hợp để đi lâu dài?", nhanDuoc: "Kiểu người thu hút mình vs kiểu người thật sự hợp lâu dài; hai kiểu giống hay khác nhau, vì sao", yBatBuoc: "Thu hút + Hợp lâu dài + Chênh lệch", cung: ["Phu Thê", "Mệnh", "Thiên Di"], yeuToThem: "Chính tinh Phu Thê; Đào Hoa, Hồng Loan, Thiên Riêu, Mộc Dục", van: [], khongDuoc: "" },
  { id: "TD04", loai: "chuyen-sau", chuDe: "tinh-duyen", cauHoi: "Người bạn đời của tôi có xu hướng là người như thế nào?", nhanDuoc: "Tính cách, năng lực, công việc, nền tảng, khí chất; lớn hay nhỏ tuổi hơn, gần hay xa quê nếu luận được", yBatBuoc: "Chân dung xu hướng", cung: [], yeuToThem: "Chính tinh và phụ tinh tại Phu Thê; xung Quan Lộc", van: [], khongDuoc: "Không mô tả ngoại hình như sự thật" },
  { id: "TD05", loai: "chuyen-sau", chuDe: "tinh-duyen", cauHoi: "Tôi dễ gặp người quan trọng của đời mình trong hoàn cảnh nào?", nhanDuoc: "Công việc, bạn bè, đi xa, học hành, gia đình, môi trường chuyên môn…", yBatBuoc: "Hoàn cảnh dễ gặp + Dấu hiệu", cung: ["Phu Thê", "Thiên Di", "Nô Bộc", "Quan Lộc"], yeuToThem: "Tam phương Phu Thê; Thiên Mã; Hồng Loan, Thiên Hỷ", van: [], khongDuoc: "" },
  { id: "TD06", loai: "chuyen-sau", chuDe: "tinh-duyen", cauHoi: "Duyên kết hôn thường đến sớm hay muộn?", nhanDuoc: "Cửa kết hôn, khoảng tuổi, có dễ yêu lâu mới cưới không, có lỡ một cửa rồi đến cửa khác không", yBatBuoc: "Đáp + Khi nào", cung: [], yeuToThem: "Tuần/Triệt tại Phu Thê; lưu Hồng Loan, Thiên Hỷ, Đào Hoa", van: ["chuoi", "th3"], khongDuoc: "Không phán ngày cưới; năm luôn ở mức gợi ý" },
  { id: "TD07", loai: "chuyen-sau", chuDe: "tinh-duyen", cauHoi: "Hôn nhân của tôi dễ gặp thử thách lớn nhất ở đâu, và thường ổn định hay có biến động?", nhanDuoc: "Thử thách chính (tiền, gia đình, xa cách, sự nghiệp, tính cách, người thứ ba, con cái) + xu hướng ổn định / dễ khủng hoảng / đứt nối / tái hợp", yBatBuoc: "Thử thách chính + Xu hướng", cung: ["Phu Thê", "Quan Lộc", "Mệnh", "Phúc Đức"], yeuToThem: "Sát tinh, Hóa Kỵ, Cô Thần, Quả Tú tại Phu Thê; xung Quan Lộc", van: ["chuoi"], khongDuoc: "Không khẳng định ly hôn hay ngoại tình — chỉ nói xu hướng và điều kiện" },
  { id: "TD08", loai: "chuyen-sau", chuDe: "tinh-duyen", cauHoi: "Bạn đời sẽ thay đổi cuộc đời tôi theo hướng nào?", nhanDuoc: "Tiền, sự nghiệp, nơi sống, quan hệ, tinh thần", yBatBuoc: "Đáp + Mặt đời đổi nhiều nhất", cung: ["Phu Thê", "Quan Lộc", "Tài Bạch"], yeuToThem: "Lộc Tồn, Hóa Lộc tại Phu Thê", van: [], khongDuoc: "" },
  // con-cai — viết lại 26/09/2026 theo luồng chủ dự án (Pain point → Narrative → Prediction)
  { id: "CC01", loai: "chuyen-sau", chuDe: "con-cai", cauHoi: "Duyên con cái của tôi nhìn chung thuận hay cần nhiều thời gian?", nhanDuoc: "Thuận / cần thời gian / cần chăm lo; xu hướng ít hay đông con CHỈ khi tín hiệu rõ", yBatBuoc: "Đáp + Mức", cung: [], yeuToThem: "Chính tinh, sát tinh tại Tử Tức; Thai, Dưỡng", van: [], khongDuoc: "Không nói con số cụ thể, không nói con trai hay gái" },
  { id: "CC02", loai: "chuyen-sau", chuDe: "con-cai", cauHoi: "Duyên con thường đến sớm hay muộn?", nhanDuoc: "Sớm / muộn + khoảng thời gian thuận", yBatBuoc: "Đáp + Khi nào", cung: [], yeuToThem: "Tuần/Triệt tại Tử Tức; đại vận đi qua Tử Tức", van: ["chuoi"], khongDuoc: "" },
  { id: "CC03", loai: "chuyen-sau", chuDe: "con-cai", cauHoi: "Con cái của tôi thường có khí chất và tiềm năng thế nào?", nhanDuoc: "Cá tính, độc lập, học hành, sự nghiệp, gần hay xa nhà", yBatBuoc: "Chân dung xu hướng", cung: [], yeuToThem: "Chính tinh Tử Tức; không có chính tinh thì mượn Điền Trạch", van: [], khongDuoc: "" },
  { id: "CC04", loai: "chuyen-sau", chuDe: "con-cai", cauHoi: "Quan hệ giữa tôi và con dễ gần gũi hay có những giai đoạn xa cách?", nhanDuoc: "Theo thời gian: lúc con nhỏ, khi con trưởng thành, về sau", yBatBuoc: "Đáp theo dòng thời gian", cung: ["Tử Tức", "Mệnh"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "CC05", loai: "chuyen-sau", chuDe: "con-cai", cauHoi: "Con cái có làm thay đổi vận đời của tôi đáng kể không?", nhanDuoc: "Tiền, sự nghiệp, nơi ở, hôn nhân, ưu tiên sống", yBatBuoc: "Đáp + Mặt đời đổi nhiều nhất", cung: ["Tử Tức", "Mệnh", "Điền Trạch"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "CC06", loai: "chuyen-sau", chuDe: "con-cai", cauHoi: "Về sau tôi có được con cái nâng đỡ không?", nhanDuoc: "Mức nâng đỡ về sau và kiểu nâng đỡ", yBatBuoc: "Đáp", cung: ["Tử Tức", "Điền Trạch"], yeuToThem: "Đại vận cuối", van: ["chuoi"], khongDuoc: "" },
  // gia-dinh — viết lại 26/09/2026 theo luồng chủ dự án (Pain point → Narrative → Prediction)
  { id: "GD01", loai: "chuyen-sau", chuDe: "gia-dinh", cauHoi: "Tôi sinh ra với nền tảng gia đình như thế nào?", nhanDuoc: "Ổn định hay biến động, vật chất, nề nếp, ảnh hưởng lớn hay nhỏ", yBatBuoc: "Đáp + Biểu hiện", cung: [], yeuToThem: "Chính tinh Phụ Mẫu; Âm Dương thuận lý", van: [], khongDuoc: "Không bịa nghề của cha mẹ nếu không có căn cứ; không luận sinh tử cha mẹ" },
  { id: "GD02", loai: "chuyen-sau", chuDe: "gia-dinh", cauHoi: "Tôi được gia đình nâng đỡ đến đâu, và phần nào phải tự thân?", nhanDuoc: "Tiền, học, quan hệ, nghề, nhà cửa — phần được đỡ và phần tự lo", yBatBuoc: "Được đỡ + Tự thân", cung: ["Phụ Mẫu", "Điền Trạch", "Mệnh"], yeuToThem: "Hóa Khoa, Ân Quang, Thiên Quý tại Phụ Mẫu", van: [], khongDuoc: "" },
  { id: "GD03", loai: "chuyen-sau", chuDe: "gia-dinh", cauHoi: "Mối quan hệ của tôi với cha và với mẹ khác nhau thế nào?", nhanDuoc: "Tách riêng cha và mẹ", yBatBuoc: "Cha + Mẹ", cung: [], yeuToThem: "Thái Dương (cha), Thái Âm (mẹ) theo độ sáng; chính tinh Phụ Mẫu", van: [], khongDuoc: "" },
  { id: "GD04", loai: "chuyen-sau", chuDe: "gia-dinh", cauHoi: "Gia đình gốc dễ là nguồn lực hay áp lực trong đời tôi?", nhanDuoc: "Tài chính, trách nhiệm, kỳ vọng, sức khỏe cha mẹ, tài sản", yBatBuoc: "Đáp + Mặt nào", cung: ["Phụ Mẫu", "Phúc Đức", "Mệnh"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "GD05", loai: "chuyen-sau", chuDe: "gia-dinh", cauHoi: "Càng trưởng thành tôi gần hay xa gia đình hơn, và về sau có phải gánh nhiều trách nhiệm với cha mẹ không?", nhanDuoc: "Gần xa về địa lý, cảm xúc; trách nhiệm về sau", yBatBuoc: "Đáp theo thời gian", cung: ["Phụ Mẫu", "Thiên Di"], yeuToThem: "", van: ["chuoi"], khongDuoc: "" },
  // anh-em — viết lại 26/09/2026 theo luồng chủ dự án (Pain point → Narrative → Prediction)
  { id: "AE01", loai: "chuyen-sau", chuDe: "anh-em", cauHoi: "Quan hệ anh chị em của tôi nhìn chung thuộc kiểu nào?", nhanDuoc: "Hòa thuận / xa cách / nhiều va chạm; ai hay là người gánh", yBatBuoc: "Đáp + Kiểu", cung: [], yeuToThem: "Chính tinh, sát tinh tại Huynh Đệ", van: [], khongDuoc: "Không nói số anh chị em" },
  { id: "AE02", loai: "chuyen-sau", chuDe: "anh-em", cauHoi: "Khi trưởng thành, chúng tôi có xu hướng gần nhau hay mỗi người một hướng?", nhanDuoc: "Diễn biến theo thời gian", yBatBuoc: "Đáp theo thời gian", cung: ["Huynh Đệ", "Thiên Di"], yeuToThem: "", van: ["chuoi"], khongDuoc: "" },
  { id: "AE03", loai: "chuyen-sau", chuDe: "anh-em", cauHoi: "Khi có chuyện lớn, anh chị em có thật sự giúp được nhau không?", nhanDuoc: "Mức giúp đỡ và kiểu giúp", yBatBuoc: "Đáp", cung: ["Huynh Đệ", "Nô Bộc"], yeuToThem: "Huynh Đệ không có chính tinh thì mượn Nô Bộc", van: [], khongDuoc: "" },
  { id: "AE04", loai: "chuyen-sau", chuDe: "anh-em", cauHoi: "Tiền bạc, tài sản hay trách nhiệm gia đình có dễ làm nảy sinh mâu thuẫn không?", nhanDuoc: "Nguồn mâu thuẫn dễ gặp", yBatBuoc: "Đáp + Tình huống", cung: ["Huynh Đệ", "Tài Bạch", "Điền Trạch"], yeuToThem: "Không Kiếp, Kình Đà, Hóa Kỵ tại Huynh Đệ", van: [], khongDuoc: "" },
  { id: "AE05", loai: "chuyen-sau", chuDe: "anh-em", cauHoi: "Có nên làm ăn hoặc giữ tài sản chung với anh chị em không?", nhanDuoc: "Nên / không nên / có điều kiện", yBatBuoc: "Đáp có điều kiện", cung: ["Huynh Đệ", "Tài Bạch"], yeuToThem: "", van: [], khongDuoc: "" },
  // quy-nhan — viết lại 26/09/2026 theo luồng chủ dự án (Pain point → Narrative → Prediction)
  { id: "QN01", loai: "chuyen-sau", chuDe: "quy-nhan", cauHoi: "Tôi có phải kiểu người thường được người khác giúp lúc cần không?", nhanDuoc: "Mức vận quý nhân chung", yBatBuoc: "Đáp + Mức", cung: [], yeuToThem: "Vị trí Khôi Việt, Tả Hữu, Thiên Quan, Thiên Phúc, Hóa Khoa trên cả lá", van: [], khongDuoc: "" },
  { id: "QN02", loai: "chuyen-sau", chuDe: "quy-nhan", cauHoi: "Quý nhân của tôi thường là kiểu người nào?", nhanDuoc: "Tuổi, vị thế, nghề, quan hệ, gần hay xa (giới chỉ khi có căn cứ)", yBatBuoc: "Chân dung quý nhân", cung: ["Nô Bộc", "Phụ Mẫu", "Thiên Di"], yeuToThem: "Khôi Việt (người đi trước), Tả Hữu (người đồng hành)", van: [], khongDuoc: "" },
  { id: "QN03", loai: "chuyen-sau", chuDe: "quy-nhan", cauHoi: "Quý nhân thường xuất hiện vào những bước ngoặt nào?", nhanDuoc: "Hoàn cảnh và giai đoạn quý nhân xuất hiện", yBatBuoc: "Đáp + Khi nào", cung: ["Nô Bộc"], yeuToThem: "Đại vận đi qua cung có Khôi Việt, Tả Hữu", van: ["chuoi"], khongDuoc: "" },
  { id: "QN04", loai: "chuyen-sau", chuDe: "quy-nhan", cauHoi: "Bạn bè, cộng sự nhìn chung mang lợi hay dễ gây phiền cho tôi — và tôi dễ gặp rắc rối vì kiểu người nào?", nhanDuoc: "Cân lợi – phiền; kiểu người dễ gây rắc rối", yBatBuoc: "Cân bằng + Kiểu người cần dè chừng", cung: ["Nô Bộc", "Huynh Đệ", "Thiên Di"], yeuToThem: "Sát tinh, Hóa Kỵ tại Nô Bộc, Huynh Đệ", van: [], khongDuoc: "Không gọi thẳng \"tiểu nhân\" mọi lúc" },
  { id: "QN05", loai: "chuyen-sau", chuDe: "quy-nhan", cauHoi: "Khách hàng, cấp dưới và người cộng tác có giúp tôi tạo tài lộc không?", nhanDuoc: "Mức và kiểu", yBatBuoc: "Đáp", cung: ["Nô Bộc", "Tài Bạch", "Quan Lộc"], yeuToThem: "Chính tinh, tứ hóa tại Nô Bộc", van: [], khongDuoc: "" },
  // phuc-duc — viết lại 26/09/2026 theo luồng chủ dự án (Pain point → Narrative → Prediction)
  { id: "PD01", loai: "chuyen-sau", chuDe: "phuc-duc", cauHoi: "Nền phúc của gia đình, dòng họ ảnh hưởng đời tôi mạnh đến đâu?", nhanDuoc: "Mức và kiểu ảnh hưởng", yBatBuoc: "Đáp + Mức", cung: [], yeuToThem: "Chính tinh, sát tinh tại Phúc Đức; Thiên Đức, Nguyệt Đức", van: [], khongDuoc: "" },
  { id: "PD02", loai: "chuyen-sau", chuDe: "phuc-duc", cauHoi: "Tôi có phải kiểu người thường gặp đường thoát khi rơi vào tình huống khó không?", nhanDuoc: "Mức và kiểu \"được cứu\"", yBatBuoc: "Đáp + Tình huống", cung: ["Phúc Đức", "Mệnh", "Tật Ách"], yeuToThem: "Giải Thần, Thiên Giải, Thiên Quan, Thiên Phúc, Thiên Đức, Nguyệt Đức", van: [], khongDuoc: "" },
  { id: "PD03", loai: "chuyen-sau", chuDe: "phuc-duc", cauHoi: "Trong dòng họ có xu hướng nào lặp lại qua nhiều thế hệ?", nhanDuoc: "Học hành, kinh doanh, ly hương, tài sản, gia đình — chỉ khi đủ căn cứ", yBatBuoc: "Đáp (nếu đủ căn cứ)", cung: ["Phúc Đức", "Phụ Mẫu", "Điền Trạch"], yeuToThem: "", van: [], khongDuoc: "Không sáng tác lịch sử dòng họ" },
  { id: "PD04", loai: "chuyen-sau", chuDe: "phuc-duc", cauHoi: "Điều gì trong đời tôi thường \"được cứu\", và điều gì dễ kéo dài thành gánh nặng?", nhanDuoc: "Mặt đời được đỡ + mặt đời dễ thành gánh", yBatBuoc: "Được cứu + Gánh nặng", cung: ["Phúc Đức", "Tật Ách", "Mệnh"], yeuToThem: "", van: ["dv"], khongDuoc: "" },
  { id: "PD05", loai: "chuyen-sau", chuDe: "phuc-duc", cauHoi: "Càng về sau đời tôi nhẹ đi hay vẫn bôn ba, hậu vận thiên về điều gì?", nhanDuoc: "Xu hướng hậu vận: an ổn, sung túc, gia đình hay tiếp tục sự nghiệp", yBatBuoc: "Đáp theo thời gian", cung: ["Phúc Đức", "THAN"], yeuToThem: "", van: ["chuoi"], khongDuoc: "KHÔNG luận thọ yểu" },
  // suc-khoe — viết lại 26/09/2026 theo luồng chủ dự án (Pain point → Narrative → Prediction)
  { id: "SK01", loai: "chuyen-sau", chuDe: "suc-khoe", cauHoi: "Thể trạng tổng thể của tôi thuộc kiểu khỏe bền hay dễ có những giai đoạn suy rõ?", nhanDuoc: "Sức bền, khả năng hồi phục, bệnh vặt hay kéo dài, xu hướng theo tuổi", yBatBuoc: "Đáp + Kiểu thể trạng", cung: [], yeuToThem: "Chính tinh Tật Ách; sát tinh; ngũ hành Mệnh – Cục", van: [], khongDuoc: "" },
  { id: "SK02", loai: "chuyen-sau", chuDe: "suc-khoe", cauHoi: "Những bộ phận hoặc nhóm vấn đề sức khỏe nào đáng chú ý nhất?", nhanDuoc: "2–3 nhóm cơ quan / vùng đáng lưu ý hơn cả, XẾP theo mức đáng lưu ý, kèm căn cứ — không ném một danh sách dài", yBatBuoc: "Xếp hạng nhóm đáng lưu ý", cung: ["Tật Ách", "Mệnh", "Phúc Đức"], yeuToThem: "Ngũ hành của chính tinh và sát tinh tại Tật Ách (Hỏa – tim mạch, huyết áp; Thủy – thận, tiết niệu; Mộc – gan mật; Kim – hô hấp; Thổ – tiêu hóa) theo quan niệm truyền thống; Kình Đà, Hỏa Linh, Không Kiếp, Hóa Kỵ", van: [], khongDuoc: "Nói là xu hướng đáng chú ý hơn, không khẳng định sẽ mắc, không chẩn đoán" },
  { id: "SK03", loai: "chuyen-sau", chuDe: "suc-khoe", cauHoi: "Vấn đề sức khỏe của tôi nếu xuất hiện thường thuộc kiểu âm ỉ, tái phát hay đột ngột?", nhanDuoc: "Mãn tính / tái phát / cấp tính / suy giảm theo tuổi", yBatBuoc: "Đáp + Biểu hiện", cung: ["Tật Ách", "Phúc Đức"], yeuToThem: "Đà La, Hóa Kỵ (âm ỉ, dai dẳng); Kình Dương, Hỏa Tinh (đột ngột); Tuần Triệt", van: [], khongDuoc: "" },
  { id: "SK04", loai: "chuyen-sau", chuDe: "suc-khoe", cauHoi: "Tôi có dấu hiệu dễ gặp tai nạn, thương tích hoặc can thiệp y khoa không?", nhanDuoc: "CHỈ luận mạnh khi tín hiệu rõ; nếu có: hoàn cảnh, loại nguy cơ, giai đoạn", yBatBuoc: "Đáp (mức tín hiệu)", cung: ["Tật Ách", "Thiên Di", "Mệnh"], yeuToThem: "Kình Dương, Thiên Hình, Linh Tinh, Hỏa Tinh; Lưu Hà", van: [], khongDuoc: "Không dọa; tín hiệu yếu thì nói là yếu" },
  { id: "SK05", loai: "chuyen-sau", chuDe: "suc-khoe", cauHoi: "Những giai đoạn tuổi nào sức khỏe cần theo dõi kỹ hơn?", nhanDuoc: "Các giai đoạn và vì sao", yBatBuoc: "Dòng thời gian", cung: ["Tật Ách"], yeuToThem: "Đại vận, tiểu hạn đi qua Tật Ách hoặc gặp sát tinh, Hóa Kỵ, Bạch Hổ, Thiên Hình", van: ["chuoi"], khongDuoc: "" },
  { id: "SK06", loai: "chuyen-sau", chuDe: "suc-khoe", cauHoi: "Riêng năm nay, sức khỏe có điểm nào đáng lưu ý?", nhanDuoc: "Nhóm cơ quan, mệt mỏi, thương tích, tháng đáng lưu ý", yBatBuoc: "Đáp + Khi nào", cung: ["TH"], yeuToThem: "Lưu tứ hóa, lưu sát tinh vào Tật Ách; tiểu hạn", van: ["th"], khongDuoc: "" },
  // nha-cua — viết lại 26/09/2026 theo luồng chủ dự án (Pain point → Narrative → Prediction)
  { id: "NC01", loai: "chuyen-sau", chuDe: "nha-cua", cauHoi: "Tôi có duyên tạo dựng nhà cửa và tài sản cố định không?", nhanDuoc: "Mức duyên và kiểu", yBatBuoc: "Đáp + Mức", cung: [], yeuToThem: "Lộc Tồn, Hóa Lộc, Đường Phù; Không Kiếp, Hóa Kỵ tại Điền Trạch", van: [], khongDuoc: "" },
  { id: "NC02", loai: "chuyen-sau", chuDe: "nha-cua", cauHoi: "Nhà cửa của tôi chủ yếu đến từ tự thân, gia đình hay hôn nhân?", nhanDuoc: "Nguồn chính của nhà cửa", yBatBuoc: "Đáp + Nguồn", cung: ["Điền Trạch", "Phụ Mẫu", "Phu Thê"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "NC03", loai: "chuyen-sau", chuDe: "nha-cua", cauHoi: "Tôi thường an cư sớm hay phải đổi chỗ vài lần mới ổn định — và có xu hướng sở hữu một nơi ở hay nhiều tài sản?", nhanDuoc: "Đường an cư + tiềm năng sở hữu", yBatBuoc: "Đáp + Kiểu", cung: ["Điền Trạch", "Thiên Di"], yeuToThem: "Thiên Mã, Phá Quân tại Điền Trạch", van: ["chuoi"], khongDuoc: "" },
  { id: "NC04", loai: "chuyen-sau", chuDe: "nha-cua", cauHoi: "Tôi có duyên kiếm tiền từ bất động sản không?", nhanDuoc: "Có / không / có điều kiện", yBatBuoc: "Đáp có điều kiện", cung: ["Điền Trạch", "Tài Bạch"], yeuToThem: "Hóa Kỵ (giấy tờ), Không Kiếp tại Điền Trạch", van: ["dv"], khongDuoc: "Không tư vấn tài chính" },
  { id: "NC05", loai: "chuyen-sau", chuDe: "nha-cua", cauHoi: "Giai đoạn nào dễ xuất hiện chuyện lớn về nhà cửa?", nhanDuoc: "Mua, bán, xây, chuyển, thừa hưởng, tranh chấp — ở giai đoạn nào", yBatBuoc: "Dòng thời gian", cung: ["Điền Trạch"], yeuToThem: "Đại vận đi qua Điền Trạch; lưu Hóa Lộc, Hóa Kỵ vào Điền Trạch", van: ["chuoi", "th3"], khongDuoc: "" },
  // ra-ngoai — viết lại 26/09/2026 theo luồng chủ dự án (Pain point → Narrative → Prediction)
  { id: "RN01", loai: "chuyen-sau", chuDe: "ra-ngoai", cauHoi: "Khi bước ra xã hội, vận của tôi tốt hơn hay khó hơn khi ở môi trường quen?", nhanDuoc: "So ra ngoài với ở chỗ quen", yBatBuoc: "Đáp + Kiểu", cung: [], yeuToThem: "Chính tinh Thiên Di; Tả Hữu, Khôi Việt", van: [], khongDuoc: "" },
  { id: "RN02", loai: "chuyen-sau", chuDe: "ra-ngoai", cauHoi: "Tôi có duyên đi xa hoặc sống xa quê không?", nhanDuoc: "Mức duyên đi xa trong nước", yBatBuoc: "Đáp", cung: [], yeuToThem: "Thiên Mã, Lộc Mã", van: ["chuoi"], khongDuoc: "" },
  { id: "RN03", loai: "chuyen-sau", chuDe: "ra-ngoai", cauHoi: "Tôi có duyên xuất ngoại không?", nhanDuoc: "Mức duyên ra nước ngoài (học, làm, sống) — tách riêng khỏi đi xa trong nước", yBatBuoc: "Đáp + Kiểu đi", cung: ["Thiên Di", "Mệnh", "Quan Lộc"], yeuToThem: "Thiên Mã, Lộc Tồn; sát tinh ở Thiên Di", van: ["chuoi"], khongDuoc: "" },
  { id: "RN04", loai: "chuyen-sau", chuDe: "ra-ngoai", cauHoi: "Nếu đi xa, điều gì dễ đưa tôi đi — và đi xa có thật sự làm vận tôi tốt lên không?", nhanDuoc: "Lý do đi (việc, học, tình cảm, kinh doanh, gia đình) + có khả năng đi ≠ đi sẽ phát", yBatBuoc: "Lý do + Có phát không", cung: ["Thiên Di", "Quan Lộc", "Phu Thê"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "RN05", loai: "chuyen-sau", chuDe: "ra-ngoai", cauHoi: "Tôi có xu hướng định cư lâu dài nơi khác hay cuối cùng vẫn quay về?", nhanDuoc: "Kết cục lâu dài", yBatBuoc: "Đáp", cung: ["Thiên Di", "Điền Trạch"], yeuToThem: "", van: ["chuoi"], khongDuoc: "" },
  { id: "RN06", loai: "chuyen-sau", chuDe: "ra-ngoai", cauHoi: "Khi ra ngoài, tôi dễ gặp quý nhân hay thị phi?", nhanDuoc: "Cơ hội và rủi ro ngoài xã hội", yBatBuoc: "Đáp + Tình huống", cung: [], yeuToThem: "Lưu Hà, Thiên Hình, sát tinh tại Thiên Di; Khôi Việt", van: ["th"], khongDuoc: "Không dọa tai nạn" },
  // hoc-van — viết lại 26/09/2026 theo luồng chủ dự án (Pain point → Narrative → Prediction)
  { id: "HV01", loai: "chuyen-sau", chuDe: "hoc-van", cauHoi: "Đường học hành của tôi nhìn chung thuận hay có nhiều lần gián đoạn?", nhanDuoc: "Mức thuận và kiểu", yBatBuoc: "Đáp", cung: ["Quan Lộc", "Phụ Mẫu", "Mệnh"], yeuToThem: "Văn tinh (xem chủ đề)", van: [], khongDuoc: "" },
  { id: "HV02", loai: "chuyen-sau", chuDe: "hoc-van", cauHoi: "Tôi mạnh về thi cử, nghiên cứu hay học qua thực tế?", nhanDuoc: "Dạng năng lực học tập", yBatBuoc: "Đáp + Biểu hiện", cung: ["Mệnh", "Quan Lộc"], yeuToThem: "Xương Khúc (thi cử, chữ nghĩa), Thiên Cơ (nghiên cứu), Thất Sát / Phá Quân (học qua làm)", van: [], khongDuoc: "Không biến thành lời khuyên phương pháp học" },
  { id: "HV03", loai: "chuyen-sau", chuDe: "hoc-van", cauHoi: "Tôi có duyên với bằng cấp, chứng chỉ không, và có thể học lên cao đến đâu?", nhanDuoc: "Duyên bằng cấp + mức học cao (chỉ nói khi luận được)", yBatBuoc: "Đáp", cung: ["Quan Lộc", "Phụ Mẫu"], yeuToThem: "Hóa Khoa, Khôi Việt, Tấu Thư, Bác Sĩ", van: [], khongDuoc: "" },
  { id: "HV04", loai: "chuyen-sau", chuDe: "hoc-van", cauHoi: "Học hành có phải yếu tố quyết định thành công của tôi không?", nhanDuoc: "Số mạnh bằng cấp hay thành công sau khi ra khỏi trường", yBatBuoc: "Đáp + Vì sao", cung: ["Quan Lộc", "Mệnh", "Tài Bạch"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "HV05", loai: "chuyen-sau", chuDe: "hoc-van", cauHoi: "Tôi có duyên học tập hoặc lấy bằng ở nước ngoài không?", nhanDuoc: "Mức duyên", yBatBuoc: "Đáp", cung: ["Thiên Di", "Quan Lộc"], yeuToThem: "Thiên Mã; Hóa Khoa ở Thiên Di", van: ["chuoi"], khongDuoc: "" },
  { id: "HV06", loai: "chuyen-sau", chuDe: "hoc-van", cauHoi: "Giai đoạn nào thuận cho học, thi và lấy chứng chỉ?", nhanDuoc: "Các giai đoạn thuận", yBatBuoc: "Dòng thời gian", cung: ["Quan Lộc", "Phụ Mẫu"], yeuToThem: "Đại vận có văn tinh, Hóa Khoa", van: ["chuoi", "dv"], khongDuoc: "" },
  // van-han — viết lại 26/09/2026 theo luồng chủ dự án (Pain point → Narrative → Prediction)
  { id: "VH01", loai: "chuyen-sau", chuDe: "van-han", cauHoi: "Nhìn toàn đời, đâu là những bước ngoặt lớn nhất?", nhanDuoc: "Cốt truyện cuộc đời (tuổi trẻ đổi hướng / trung vận bật / sau tích tài sản / hậu vận…) — KHÔNG bắt đầu bằng bảng mười năm", yBatBuoc: "Cốt truyện + Bước ngoặt", cung: ["Mệnh"], yeuToThem: "Tam phương mỗi cung vận so với nguyên cục", van: ["chuoi"], khongDuoc: "" },
  { id: "VH02", loai: "chuyen-sau", chuDe: "van-han", cauHoi: "Các chặng 10 năm của đời tôi lần lượt mang chủ đề gì?", nhanDuoc: "Mỗi chặng: chủ đề, cơ hội, rủi ro, loại chuyện dễ nổi lên", yBatBuoc: "Từng chặng", cung: ["Mệnh"], yeuToThem: "Tam phương mỗi cung vận so với nguyên cục", van: ["chuoi"], khongDuoc: "" },
  { id: "VH03", loai: "chuyen-sau", chuDe: "van-han", cauHoi: "Tôi đang ở chặng nào của cuộc đời?", nhanDuoc: "Chặng hiện tại thiên về mở rộng / thay đổi / tích lũy / thử thách / thu hoạch", yBatBuoc: "Đáp + Vì sao", cung: ["DV"], yeuToThem: "Tam phương cung vận; sao nguyên cục tại cung vận", van: ["dv"], khongDuoc: "" },
  { id: "VH04", loai: "chuyen-sau", chuDe: "van-han", cauHoi: "Những việc lớn nào dễ xảy ra trong giai đoạn 10 năm hiện tại?", nhanDuoc: "Chọn các tín hiệu mạnh nhất: việc, tiền, cưới, con, nhà, đi xa, sức khỏe", yBatBuoc: "Các việc dễ xảy ra", cung: ["DV"], yeuToThem: "Tam phương cung vận; lưu tứ hóa các năm trong vận", van: ["dv"], khongDuoc: "" },
  { id: "VH05", loai: "chuyen-sau", chuDe: "van-han", cauHoi: "Riêng năm nay, chủ đề lớn nhất và những việc dễ nổi lên nhất là gì?", nhanDuoc: "Chủ đề năm + 3–5 khả năng đáng chú ý nhất (đổi việc, khoản chi / tài sản lớn, tình cảm sang trạng thái mới, đi xa, sức khỏe…)", yBatBuoc: "Chủ đề + Các khả năng", cung: ["TH"], yeuToThem: "Lưu Thái Tuế; lưu tứ hóa theo can năm; đối chiếu đại vận", van: ["th", "dv"], khongDuoc: "Năm luôn ở mức gợi ý" },
  { id: "VH06", loai: "chuyen-sau", chuDe: "van-han", cauHoi: "Cơ hội lớn nhất và rủi ro lớn nhất của năm nay nằm ở đâu?", nhanDuoc: "Một cơ hội + một rủi ro, không né", yBatBuoc: "Cơ hội + Rủi ro", cung: ["TH"], yeuToThem: "Như VH05", van: ["th", "dv"], khongDuoc: "" },
  { id: "VH07", loai: "chuyen-sau", chuDe: "van-han", cauHoi: "Nhịp của năm nay thay đổi thế nào qua từng giai đoạn?", nhanDuoc: "Đầu năm / giữa năm / cuối năm (hoặc theo tháng): lĩnh vực nào dễ biến động — không chỉ \"tháng tốt / xấu\"", yBatBuoc: "Từng giai đoạn", cung: ["TH"], yeuToThem: "Nguyệt hạn đếm từ tiểu hạn", van: ["th", "nguyet"], khongDuoc: "" },
  { id: "VH08", loai: "chuyen-sau", chuDe: "van-han", cauHoi: "Ba năm tới đang dẫn tôi đến đâu?", nhanDuoc: "Một câu chuyện liên năm: năm đầu xuất hiện tín hiệu → năm sau buộc phải quyết → năm thứ ba thành kết quả — không phải ba lời bói rời", yBatBuoc: "Câu chuyện liên năm", cung: ["TH"], yeuToThem: "Như VH05", van: ["th3", "dv"], khongDuoc: "" },
];
