/**
 * KHUNG CÂU HỎI v3. Bản gốc sinh từ KHUNG-LUAN-GIAI-v3.xlsx (chủ dự án duyệt
 * 23/09/2026). Từ khung 2026.09.5 (30/09/2026) phần CHUYÊN SÂU được tinh gọn
 * thẳng ở đây: 14 chủ đề / ~80 câu → 9 chủ đề / 29 câu, câu hỏi khái quát theo
 * một mạch, chi tiết cụ thể nằm trong câu trả lời. Tệp này đi TRƯỚC tệp xlsx;
 * sửa xlsx mà không sửa tệp này là không có tác dụng.
 *
 * Token cung đặc biệt: "THAN" = cung an Thân, "DV" = cung đại vận đang chạy,
 * "TH" = cung tiểu hạn của năm xem.
 */

export type LopVan = 'dv' | 'chuoi' | 'th' | 'th3' | 'nguyet' | 'diem';

export interface ChuDeV3 {
  ma: string;
  id: string;
  ten: string;
  cungChinh: string;
  phuTro: { cung: string; vaiTro: string }[];
  saoToanCuc: string;
}

export interface CauHoiV3 {
  id: string;
  loai: 'tong-quan' | 'chuyen-sau';
  chuDe: string;
  cauHoi: string;
  nhanDuoc: string;
  /** Những ý bài phải có — lấy từ cột "Ý bắt buộc phải có" / "Cung & yếu tố" */
  yBatBuoc: string;
  /** Cung phải đọc, theo thứ tự ưu tiên. Rỗng = cung chính của chủ đề + tam phương */
  cung: string[];
  yeuToThem: string;
  van: LopVan[];
  khongDuoc: string;
  /**
   * Chi tiết cụ thể câu trả lời NÊN có — CHỈ khi một đoạn nguồn nói rõ chi tiết
   * ấy cho đúng tổ hợp của lá số (30/09/2026, chủ dự án: "có căn cứ thì phải
   * trả lời, không có thì không được bịa"). Không phải chỉ tiêu bắt buộc.
   */
  chiTiet?: string;
  /** Cung chính của RIÊNG câu này khi khác cung chính của chủ đề (câu gộp từ chủ đề cũ) */
  cungChinh?: string;
  /** Chủ đề cũ mà truy hồi mượn từ khoá (câu gộp: anh em, quý nhân, học hành…) */
  tuKhoa?: string;
  /**
   * Câu có được nói mốc thời gian không (30/09/2026). "co": câu hỏi về thời điểm —
   * mốc là trọng tâm. "phu": được nhắc mốc khi dữ kiện vận có, nhưng không phải trọng
   * tâm. "khong": câu bản chất — không nêu tuổi, năm, chặng. Trước đây đoán bằng
   * regex trên câu hỏi nên SN01 "hợp nghề gì" lại bị cho nói mốc.
   */
  thoiDiem: 'co' | 'khong' | 'phu';
  /**
   * Các cung trong `cung` NGANG HÀNG, không có cung gốc (01/10/2026, TQ12). Mặc định
   * cung đầu là gốc và tam phương của nó vào trước với vai "gọn" (không kèm nghĩa sao);
   * TQ12 liệt kê Phụ Mẫu rồi Nô Bộc — mà Nô Bộc là tam hợp của Phụ Mẫu, nên nó vào
   * với vai gọn và bài luận bạn bè không có chỗ dựa, còn Tử Tức lọt vào làm nhiễu.
   * Bật cờ này: mọi cung liệt kê đều là cung chính, không kéo tam phương của cung đầu.
   */
  ngangHang?: true;
}

export const PHIEN_BAN_KHUNG_V3 = '2026.09.6';

// 30/09/2026: bỏ năm chủ đề anh-em, quy-nhan, phuc-duc, nha-cua, hoc-van — câu của chúng gộp vào chủ đề chủ
export const CHU_DE_V3: ChuDeV3[] = [
  { ma: "TC", id: "tinh-cach", ten: "Tính cách & con người", cungChinh: "Mệnh", phuTro: [{"cung": "Thân", "vaiTro": "con người từ khoảng 30 tuổi trở đi; nặng dần theo tuổi"}, {"cung": "Tật Ách", "vaiTro": "\"mệnh thứ hai\": nét tính cách ẩn, bản năng, phản ứng khi áp lực, thể chất"}, {"cung": "Phúc Đức", "vaiTro": "tư tưởng, đời sống tinh thần, cách hưởng thụ"}, {"cung": "Thiên Di", "vaiTro": "con người mình trong mắt người ngoài"}], saoToanCuc: "Chính tinh tại Mệnh + độ sáng; cách cục của tam phương Mệnh; Mệnh chủ, Thân chủ; ngũ hành bản mệnh – Cục; vòng Tràng Sinh tại Mệnh; Tuần/Triệt tại Mệnh" },
  { ma: "SN", id: "su-nghiep", ten: "Sự nghiệp & học vấn", cungChinh: "Quan Lộc", phuTro: [{"cung": "Thiên Di", "vaiTro": "môi trường bên ngoài, cơ hội nơi xa"}, {"cung": "Nô Bộc", "vaiTro": "đồng nghiệp, cấp dưới, khách hàng, quý nhân ngang hàng"}, {"cung": "Phụ Mẫu", "vaiTro": "cấp trên, cơ quan nhà nước, giấy tờ, học vấn, thầy"}, {"cung": "Huynh Đệ", "vaiTro": "người cùng hàng, cộng sự"}, {"cung": "Điền Trạch", "vaiTro": "nơi làm việc, cơ sở kinh doanh"}], saoToanCuc: "Hóa Quyền, Hóa Khoa; Khôi Việt, Tả Hữu; Xương Khúc; Thiên Mã; Quốc Ấn, Thai Phụ, Phong Cáo; Lộc Tồn; Thiên Quan, Thiên Phúc, Ân Quang, Thiên Quý; Long Trì, Phượng Các, Tấu Thư, Bác Sĩ" },
  { ma: "TB", id: "tien-bac", ten: "Tiền bạc & tài sản", cungChinh: "Tài Bạch", phuTro: [{"cung": "Điền Trạch", "vaiTro": "kho của: giữ tiền, nhà cửa, bất động sản"}, {"cung": "Thiên Di", "vaiTro": "tiền từ bên ngoài, nơi xa"}, {"cung": "Nô Bộc", "vaiTro": "tiền qua người khác: khách hàng, cấp dưới"}, {"cung": "Huynh Đệ", "vaiTro": "hùn vốn, vay mượn người thân"}, {"cung": "Phu Thê", "vaiTro": "bạn đời tác động tới tiền"}, {"cung": "Phụ Mẫu", "vaiTro": "thừa kế"}], saoToanCuc: "Lộc Tồn, Hóa Lộc (vị trí trên cả lá); Đường Phù; Địa Không, Địa Kiếp; Đại Hao, Tiểu Hao; Hóa Kỵ; Hỏa Tinh, Linh Tinh (tiền đột phát)" },
  { ma: "TD", id: "tinh-duyen", ten: "Tình duyên & hôn nhân", cungChinh: "Phu Thê", phuTro: [{"cung": "Mệnh / Thân", "vaiTro": "bản thân mình trong quan hệ đôi lứa"}, {"cung": "Tử Tức", "vaiTro": "đời sống lứa đôi, chuyện gần gũi"}, {"cung": "Điền Trạch", "vaiTro": "tổ ấm, đời sống chung"}], saoToanCuc: "Sao đào hoa trên cả lá: Đào Hoa, Hồng Loan, Thiên Hỷ, Thiên Riêu, Hàm Trì, Mộc Dục; Cô Thần, Quả Tú; Tuần/Triệt tại Phu Thê" },
  { ma: "CC", id: "con-cai", ten: "Con cái", cungChinh: "Tử Tức", phuTro: [{"cung": "Phu Thê", "vaiTro": "quan hệ với bạn đời ảnh hưởng tới con"}, {"cung": "Phúc Đức", "vaiTro": "phúc để lại cho con"}, {"cung": "Mệnh", "vaiTro": "cách mình làm cha mẹ"}], saoToanCuc: "Thai, Dưỡng (vòng Tràng Sinh); sát tinh và Tuần/Triệt tại Tử Tức — số con, trai hay gái CHỈ nêu khi nguồn nói rõ cho đúng tổ hợp" },
  { ma: "GD", id: "gia-dinh", ten: "Gia đình & phúc đức", cungChinh: "Phụ Mẫu", phuTro: [{"cung": "Huynh Đệ", "vaiTro": "anh chị em"}, {"cung": "Phúc Đức", "vaiTro": "dòng họ, tổ tiên, nền phúc, hậu vận"}, {"cung": "Điền Trạch", "vaiTro": "tổ nghiệp"}, {"cung": "Mệnh", "vaiTro": "mình trong mắt cha mẹ; phần mình tự tạo"}, {"cung": "Thái Dương / Thái Âm", "vaiTro": "vị trí và độ sáng: cha / mẹ (bất kể nằm ở cung nào)"}], saoToanCuc: "Âm Dương thuận lý hay nghịch lý; Hóa Khoa; Ân Quang, Thiên Quý; Tang Môn, Bạch Hổ, Điếu Khách; Thiên Đức, Nguyệt Đức, Long Đức, Phúc Đức; Thiên Quan, Thiên Phúc; Giải Thần, Thiên Giải" },
  { ma: "SK", id: "suc-khoe", ten: "Sức khỏe", cungChinh: "Tật Ách", phuTro: [{"cung": "Mệnh / Thân", "vaiTro": "thể chất gốc"}, {"cung": "Phúc Đức", "vaiTro": "sức bền, tinh thần"}, {"cung": "Ngũ hành bản mệnh – Cục", "vaiTro": "nền thể trạng"}], saoToanCuc: "Kình Dương, Đà La, Hỏa Tinh, Linh Tinh, Địa Không, Địa Kiếp; Hóa Kỵ; Thiên Hình; Bệnh Phù — chỉ luận XU HƯỚNG, không chẩn đoán" },
  { ma: "RN", id: "ra-ngoai", ten: "Ra ngoài, đi xa, môi trường", cungChinh: "Thiên Di", phuTro: [{"cung": "Mệnh", "vaiTro": "đối chiếu: mình ở nhà và mình ở ngoài"}, {"cung": "Điền Trạch", "vaiTro": "nơi ở, định cư"}], saoToanCuc: "Thiên Mã, Lộc Tồn (Lộc Mã); Tả Hữu, Khôi Việt; sát tinh; Lưu Hà, Thiên Hình (an toàn đi lại)" },
  { ma: "VH", id: "van-han", ten: "Vận hạn", cungChinh: "Cung đại vận / tiểu hạn", phuTro: [{"cung": "Nguyên cục", "vaiTro": "vận chỉ kích hoạt cái vốn có; luôn đối chiếu với cung gốc cùng chủ đề"}], saoToanCuc: "Tam phương tứ chính của cung vận; lưu Thái Tuế; lưu tứ hóa theo can năm; lưu Lộc Tồn, lưu Kình Đà; nguyệt hạn (tùy chọn)" },
];

export const CAU_HOI_V3: CauHoiV3[] = [
  { id: "TQ01", thoiDiem: "khong", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Tôi là người như thế nào?", nhanDuoc: "Hai hoặc ba nét tính cách rõ nhất, mỗi nét kèm một biểu hiện cụ thể (không mở bằng một nhãn một chữ cho cả con người) + một câu về mặt bên trong", yBatBuoc: "Mệnh (chính) + tam hợp Tài Bạch, Quan Lộc + xung Thiên Di; Thân; Tật Ách, Phúc Đức cho mặt bên trong", cung: ["Mệnh", "THAN", "Tật Ách", "Phúc Đức"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "TQ02", thoiDiem: "khong", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Điểm mạnh nổi bật nhất của tôi?", nhanDuoc: "Một năng lực + một lợi thế trong đời", yBatBuoc: "Cách cục cát mạnh nhất; cung có chính tinh miếu vượng + cát tinh; vị trí Hóa Lộc / Quyền / Khoa", cung: ["Mệnh", "Quan Lộc", "Tài Bạch"], yeuToThem: "", van: ["diem"], khongDuoc: "" },
  { id: "TQ03", thoiDiem: "khong", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Điều tôi cần lưu ý nhất?", nhanDuoc: "Một kiểu sai lặp lại hoặc một mặt yếu của đời", yBatBuoc: "Cung yếu nhất (chính tinh hãm + sát tinh + Hóa Kỵ); sát tinh ở Mệnh, Thân, Phúc Đức", cung: ["Mệnh", "Phúc Đức"], yeuToThem: "", van: ["diem"], khongDuoc: "" },
  // TQ12 (01/10/2026, góp ý "đọc tổng quan vẫn không biết mối quan hệ của mình ra sao"): trước đó tổng quan chỉ có
  // tình duyên (TQ07) — cha mẹ, anh chị em, bạn bè không có câu nào. Đứng ngay sau ba câu về con người để đọc liền mạch.
  { id: "TQ12", thoiDiem: "khong", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Tôi thế nào với những người quanh mình?", nhanDuoc: "Mỗi nhóm người gần (người đi trước, anh chị em, bạn bè, người ngoài) một nhận định: họ là người thế nào với bạn, ai là chỗ dựa, vướng ở đâu", yBatBuoc: "Phụ Mẫu (cha mẹ, người đi trước) + Huynh Đệ (anh chị em) + Nô Bộc (bạn bè, người cộng tác) + Thiên Di (người ngoài nhìn mình); Tả Hữu, Khôi Việt cho quý nhân", cung: ["Nô Bộc", "Phụ Mẫu", "Huynh Đệ", "Thiên Di"], ngangHang: true, yeuToThem: "", van: [], khongDuoc: "Không bàn bạn đời, tình duyên (đã có câu riêng). Không tả lại tính cách chung. Không mặc định người đọc có anh chị em hay đã gặp một người cụ thể" },
  { id: "TQ04", thoiDiem: "khong", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Lá số mạnh ở mặt nào, yếu ở mặt nào?", nhanDuoc: "Xếp 12 mặt đời vào 3 nhóm Thuận lợi / Ổn định / Cần chăm chút", yBatBuoc: "Chấm từng cung theo luật: chính tinh + độ sáng + cát/sát tinh + tứ hóa + Tuần/Triệt (engine chấm, không dùng LLM)", cung: ["Mệnh"], yeuToThem: "", van: ["diem"], khongDuoc: "" },
  { id: "TQ05", thoiDiem: "khong", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Tôi hợp hướng nghề nào?", nhanDuoc: "Một dòng: nhóm nghề + vai trò", yBatBuoc: "Quan Lộc + tam phương", cung: ["Quan Lộc"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "TQ06", thoiDiem: "khong", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Tiền bạc của tôi nói chung thế nào?", nhanDuoc: "Mức kiếm / mức giữ + nguồn chính", yBatBuoc: "Tài Bạch + tam phương + Phúc Đức (xung) + Điền Trạch", cung: ["Tài Bạch", "Phúc Đức", "Điền Trạch"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "TQ07", thoiDiem: "phu", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Tình duyên của tôi nói chung thế nào?", nhanDuoc: "Kiểu duyên + sớm hay muộn", yBatBuoc: "Phu Thê + tam phương", cung: ["Phu Thê"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "TQ08", thoiDiem: "co", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Giai đoạn 10 năm hiện tại của tôi là giai đoạn gì?", nhanDuoc: "Tên giai đoạn + chủ đề + 1 lưu ý", yBatBuoc: "Cung đại vận hiện tại + tam phương, đặt lên nguyên cục", cung: ["DV"], yeuToThem: "", van: ["dv"], khongDuoc: "" },
  { id: "TQ09", thoiDiem: "co", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Năm nay tôi cần biết gì?", nhanDuoc: "Chủ đề năm + nên / tránh", yBatBuoc: "Tiểu hạn + lưu Thái Tuế + lưu tứ hóa + đại vận", cung: ["TH"], yeuToThem: "", van: ["th", "dv"], khongDuoc: "" },
  { id: "TQ10", thoiDiem: "co", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Đường đời của tôi đi lên thế nào (tiền vận – trung vận – hậu vận)?", nhanDuoc: "Mỗi giai đoạn 10 năm 1 dòng", yBatBuoc: "Tất cả cung đại vận; Mệnh (tiền vận) vs Thân (hậu vận); Triệt (tiền vận), Tuần (hậu vận)", cung: ["Mệnh", "THAN"], yeuToThem: "", van: ["chuoi"], khongDuoc: "" },
  { id: "TQ11", thoiDiem: "phu", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Tôi nên xem sâu phần nào trước?", nhanDuoc: "2–3 chủ đề + lý do 1 dòng (sinh theo luật, không phải luận giải)", yBatBuoc: "Điểm mạnh / yếu (TQ04) + đại vận hiện tại + độ nổi bật", cung: ["Mệnh"], yeuToThem: "", van: ["diem", "dv", "chuoi"], khongDuoc: "" },
  // ===== CHUYÊN SÂU — tinh gọn 30/09/2026: 29 câu, 9 chủ đề. Câu hỏi khái quát theo một mạch; chi tiết cụ thể
  // (số, năm, trai/gái, tên nghề, bộ phận…) nằm trong câu trả lời, CHỈ khi nguồn nói rõ — cột chiTiet.
  // Câu không hỏi thời điểm thì nhanDuoc tránh chữ "khi nào / giai đoạn / tuổi / đỉnh / mốc" (từ 30/09/2026 hoiThoiDiem đọc trường thoiDiem, không đọc cột này nữa).
  // tinh-cach — gộp TC01+TC08 / TC02+TC07 / TC03–TC06
  { id: "TC01", thoiDiem: "phu", loai: "chuyen-sau", chuDe: "tinh-cach", cauHoi: "Tôi thật sự là người thế nào?", nhanDuoc: "MỘT trục chính: điều người này sống vì, cần gì để thấy yên, coi trọng điều gì nhất; bên ngoài và bên trong có vênh nhau không; người khác nhìn mình lúc đầu và khi đã thân khác nhau ra sao; con người ấy đổi khác thế nào theo tuổi, điều gì ngày càng rõ, điều gì mềm đi", yBatBuoc: "Trục chính + Người khác nhìn + Theo tuổi", cung: ["Mệnh", "Thiên Di", "THAN"], yeuToThem: "Chính tinh Mệnh + độ sáng; cách cục; phụ tinh tại Mệnh; Mệnh không có chính tinh thì mượn Thiên Di; chính tinh Thiên Di; cung Thân (nặng dần sau khoảng 30); Tuần (hậu vận) / Triệt (tiền vận) tại Mệnh, Thân", van: ["chuoi"], khongDuoc: "Không liệt kê hàng loạt tính từ. Không mô tả bằng phong cách làm việc; công việc tối đa một ví dụ phụ" },
  { id: "TC02", thoiDiem: "khong", loai: "chuyen-sau", chuDe: "tinh-cach", cauHoi: "Điểm mạnh nào tôi nên dựa vào, và điều gì hay khiến tôi tự làm khó mình?", nhanDuoc: "Phẩm chất tự nhiên nổi hơn phần đông người khác và người khác tìm đến mình vì điều gì; điểm mù, thói quen dễ lặp, lúc điểm mạnh thành điểm yếu, dễ trả giá ở mặt nào (tình cảm, tiền, quan hệ, tinh thần)", yBatBuoc: "Điểm mạnh + Hiện ra ở đâu + Điểm tự làm khó + Hệ quả", cung: ["Mệnh", "Tật Ách", "Phúc Đức"], yeuToThem: "Cát tinh trong tam phương Mệnh: Tả Hữu, Khôi Việt, Xương Khúc, Lộc Tồn, Hóa Lộc/Quyền/Khoa; sát tinh (Kình, Đà, Hỏa, Linh, Không, Kiếp), Hóa Kỵ, chính tinh hãm; Hóa Quyền, Thất Sát, Phá Quân (quyết nhanh)", van: [], khongDuoc: "Không dùng ngôn ngữ CV (\"khả năng lãnh đạo, điều phối\"). Không dọa, không gắn nhãn xấu. Không mô tả bằng phong cách làm việc; công việc tối đa một ví dụ phụ" },
  { id: "TC03", thoiDiem: "khong", loai: "chuyen-sau", chuDe: "tinh-cach", cauHoi: "Khi áp lực hay bị tổn thương, tôi thành người thế nào?", nhanDuoc: "Nhu cầu sâu và nỗi sợ nằm dưới phản ứng; thu mình, nóng lên, cắt đứt, kiểm soát hay cố tự gánh; giữ trong lòng hay nói ra, dễ tha thứ hay nhớ lâu; với người thân khác người ngoài ra sao; biến cố làm mạnh lên hay mất phương hướng", yBatBuoc: "Phản ứng + Nỗi sợ bên dưới + Người thân và người ngoài", cung: ["Tật Ách", "Phúc Đức", "Mệnh"], yeuToThem: "Tật Ách = mệnh thứ hai (bản năng); Phúc Đức = tinh thần, so với Mệnh để chỉ ra độ vênh; Cự Môn, Hóa Kỵ (khúc mắc lời nói); Thiên Riêu; Kình Đà; Tuần Triệt; Khốc Hư, Cô Quả; Tả Hữu, Thiên Lương (che chở); Thiên Đồng (dễ mềm)", van: [], khongDuoc: "Không chuyển sang lời khuyên quản lý căng thẳng. Không mô tả bằng phong cách làm việc; công việc tối đa một ví dụ phụ" },
  // su-nghiep — gộp SN01+SN03 / SN02+SN04 / SN07+SN08 / SN05+SN06+quý nhân / học vấn
  { id: "SN01", thoiDiem: "khong", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Tôi hợp làm nghề gì?", nhanDuoc: "Nêu ngay trong câu mở đầu 3–5 nhóm ngành hợp, rồi mới giải thích bằng cách tạo giá trị cốt lõi (giải quyết vấn đề, dẫn dắt, vận hành, kết nối, phân tích, xây hệ thống, sáng tạo…) và bản chất công việc hợp; thêm 1–2 nhóm ít hợp", yBatBuoc: "Nhóm ngành hợp + Vì sao hợp + Ít hợp", cung: ["Quan Lộc", "Mệnh"], yeuToThem: "Tử Vi, Thiên Phủ, Thiên Tướng (tổ chức, quản lý); Thất Sát, Phá Quân (tiên phong); Cơ Nguyệt Đồng Lương (chuyên môn, hỗ trợ); Cự Môn (dùng lời nói); Tham Lang (giao tế); Xương Khúc (chữ nghĩa), Vũ Khúc (tài chính), Thiên Mã (di chuyển), Hóa Quyền; ngũ hành Mệnh chỉ để tham khảo", van: [], khongDuoc: "Không nói \"chỉ hợp ngành X\" như định danh — người đang làm nghề khác cũng phải thấy mình trong đó", chiTiet: "Tên nghề, vị trí công việc cụ thể — nêu khi nguồn nói rõ nghề ấy cho đúng tổ hợp sao – cung của lá số" },
  { id: "SN02", thoiDiem: "khong", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Tôi hợp làm công, kinh doanh hay làm tự do?", nhanDuoc: "Mô hình hợp nhất + mô hình thứ hai; trong tổ chức thì hợp vị trí nào (chuyên gia, cố vấn, quản lý, người dẫn dắt, người vận hành), cần nhiều hay ít quyền quyết định; điều kiện để tự làm chủ tốt hơn làm công, và làm chủ quá vội dễ vướng gì", yBatBuoc: "Đáp có điều kiện + Vị trí hợp + Điều kiện tự làm chủ", cung: ["Quan Lộc", "Tài Bạch", "Mệnh", "Phụ Mẫu", "Nô Bộc", "Thiên Di"], yeuToThem: "Phụ Mẫu tốt → hợp tổ chức có cấp trên rõ; Thiên Di mạnh → hợp môi trường ngoài; Nô Bộc (khách, cấp dưới), Huynh Đệ (hùn); Tử Phủ Vũ Tướng (điều hành); Cơ Nguyệt Đồng Lương (tham mưu)", van: [], khongDuoc: "Không khẳng định chắc chắn thành hay bại" },
  { id: "SN03", thoiDiem: "phu", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Sự nghiệp của tôi khi nào lên, đỉnh ở đâu?", nhanDuoc: "Kiểu đi lên (chậm chắc / bật nhanh / vài lần chuyển hướng / chuyên môn rồi quản lý / làm công rồi tự làm); đỉnh của CÁI GÌ (chức vụ, quyền, tiền, danh tiếng) ở giai đoạn nào; chặng hiện tại đang ở đâu trên đường ấy và năm nay nghiêng về điều gì", yBatBuoc: "Kiểu đi lên + Đỉnh của gì, khi nào + Đang ở đâu", cung: ["Quan Lộc", "DV"], yeuToThem: "Hóa Quyền, Khôi Việt, Quốc Ấn, Thai Phụ, Phong Cáo; tam phương cung vận; tiểu hạn năm nay; lưu tứ hóa", van: ["chuoi", "dv", "th"], khongDuoc: "Không nêu chức danh cụ thể như sự thật; không phán đỉnh tuyệt đối", chiTiet: "Năm cụ thể của bước lên — nêu khi nguồn có luật năm và điều kiện của luật ấy khớp dữ kiện" },
  { id: "SN04", thoiDiem: "khong", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Ai giúp tôi, và điều gì cản tôi trên đường sự nghiệp?", nhanDuoc: "Người thường nâng (cấp trên / cộng sự / khách hàng / người gặp ngoài xã hội) là kiểu người nào; MỘT nút thắt chính (thiếu quyền, chọn sai môi trường, cấp trên, đổi việc, thiếu kiên nhẫn, sai đối tác, tự ái…) và dấu hiệu nhận ra sớm; va chạm công khai hay ngầm", yBatBuoc: "Người nâng + Nút thắt + Dấu hiệu", cung: ["Quan Lộc", "Phụ Mẫu", "Nô Bộc", "Huynh Đệ", "Thiên Di"], yeuToThem: "Phụ Mẫu = cấp trên; Huynh Đệ = ngang hàng; Nô Bộc = cấp dưới, khách; Khôi Việt (người đi trước), Tả Hữu (người đồng hành), Thiên Quan, Thiên Phúc; sát tinh, Hóa Kỵ, Tuần/Triệt trên tam phương Quan Lộc; Kình Đà (va chạm)", van: [], khongDuoc: "Không gọi thẳng \"tiểu nhân\"", chiTiet: "Tuổi, giới, vị thế của người nâng đỡ — nêu khi nguồn nói rõ", tuKhoa: "quy-nhan" },
  { id: "SN05", thoiDiem: "khong", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Học hành, bằng cấp của tôi đi tới đâu?", nhanDuoc: "Đường học thuận hay gián đoạn; mạnh về thi cử, nghiên cứu hay học qua thực tế; duyên bằng cấp, chứng chỉ; học hành có phải yếu tố quyết định thành công hay thành công đến sau khi ra khỏi trường", yBatBuoc: "Mức thuận + Kiểu học + Vai trò của bằng cấp", cung: ["Quan Lộc", "Phụ Mẫu", "Mệnh"], yeuToThem: "Văn Xương, Văn Khúc (thi cử, chữ nghĩa), Thiên Cơ (nghiên cứu), Thất Sát / Phá Quân (học qua làm); Hóa Khoa, Khôi Việt, Tấu Thư, Bác Sĩ, Long Trì, Phượng Các", van: [], khongDuoc: "Không biến thành lời khuyên phương pháp học hay tư vấn nghề", chiTiet: "Mức học cụ thể (đại học, sau đại học) — nêu khi nguồn nói rõ", tuKhoa: "hoc-van" },
  // tien-bac — gộp TB01+TB07 / TB02+TB05+NC04 / TB06 / TB03+TB04 / NC01–03+NC05
  { id: "TB01", thoiDiem: "khong", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Tôi có giàu không?", nhanDuoc: "Trả lời thẳng bằng một mức: đủ sống / khá giả / giàu có / biến động mạnh; kiếm dễ hay qua nhiều bước, tự thân hay có trợ lực; giàu nhờ thu nhập hay nhờ tài sản; điều kiện quan trọng nhất để chạm mức ấy", yBatBuoc: "Đáp thẳng (một mức) + Kiểu + Điều kiện", cung: ["Tài Bạch", "THAN", "Điền Trạch"], yeuToThem: "Luật chấm Tài Bạch; Tuần/Triệt tại Tài Bạch; Lộc Tồn, Hóa Lộc; cung Thân", van: [], khongDuoc: "Không nêu số tiền" },
  { id: "TB02", thoiDiem: "khong", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Tiền của tôi đến từ đâu, và làm gì thì dễ giàu?", nhanDuoc: "Nguồn thu thường xuyên và nguồn có thể tạo bước nhảy (nghề, kinh doanh, quản lý, tài sản, quan hệ, hôn nhân, thừa hưởng); hợp tích sản hay đầu cơ, dài hay ngắn hạn, kênh nào (kinh doanh, nhà đất, tài chính); thành nhờ kỹ năng hay thời vận", yBatBuoc: "Nguồn thường xuyên + Nguồn bước nhảy + Kiểu làm giàu hợp", cung: ["Tài Bạch", "Điền Trạch", "Nô Bộc", "Phu Thê", "Mệnh"], yeuToThem: "Vị trí Lộc Tồn, Hóa Lộc trên cả lá; chính tinh Tài Bạch; Thiên Phủ, Vũ Khúc (tích sản) vs Tham Lang, Phá Quân (mạo hiểm); Không Kiếp, Hỏa Linh (đột phát – đột mất); Hóa Kỵ (giấy tờ nhà đất)", van: [], khongDuoc: "Không nêu số tiền; không tư vấn mua bán tài sản cụ thể", chiTiet: "Ngành hay kênh kiếm tiền cụ thể — nêu khi nguồn nói rõ cho đúng tổ hợp" },
  { id: "TB03", thoiDiem: "co", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Khi nào là thời cơ tiền bạc của tôi, và làm sao nhận ra?", nhanDuoc: "Thời kỳ khó kiếm, thời kỳ thu nhập tăng, thời kỳ biến động, giai đoạn tích tài sản, giai đoạn dễ tạo bước nhảy; dấu hiệu nhận ra thời cơ đã tới", yBatBuoc: "Dòng thời gian + Bước nhảy + Dấu hiệu", cung: ["Tài Bạch", "Điền Trạch"], yeuToThem: "Đại vận có Lộc hoặc đi qua Tài Bạch, Điền Trạch; đại vận gặp Không Kiếp, Hóa Kỵ; lưu Hóa Lộc các năm tới", van: ["chuoi", "th3"], khongDuoc: "Không nêu số tiền", chiTiet: "Năm cụ thể của thời cơ — nêu khi nguồn có luật năm và điều kiện khớp dữ kiện" },
  { id: "TB04", thoiDiem: "khong", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Tôi giữ tiền được không, và dễ mất tiền vì đâu?", nhanDuoc: "Khả năng tích lũy; tiền hay hao vào đâu, hao chủ động hay bất ngờ; MỘT nguồn hao nổi bật nhất (quyết định nóng vội, cho vay, hùn vốn, người thân, bạn bè, bạn đời, đối tác) và tình huống dễ xảy ra", yBatBuoc: "Đáp + Chỗ hao chính + Tình huống", cung: ["Tài Bạch", "Phúc Đức", "Điền Trạch", "Huynh Đệ", "Nô Bộc", "Phu Thê"], yeuToThem: "Không Kiếp, Đại Hao, Tiểu Hao, Phá Quân, Hóa Kỵ; Lộc Tồn (giữ của); sát tinh ở Huynh Đệ, Nô Bộc", van: [], khongDuoc: "" },
  { id: "TB05", thoiDiem: "co", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Nhà cửa, tài sản của tôi đến khi nào, nhờ đâu?", nhanDuoc: "Mức duyên nhà cửa; nguồn chính (tự thân, gia đình, hôn nhân); an cư sớm hay đổi chỗ vài lần mới ổn; một nơi ở hay nhiều tài sản; giai đoạn dễ có chuyện lớn về nhà (mua, xây, chuyển, thừa hưởng, tranh chấp)", yBatBuoc: "Đáp + Nguồn + Khi nào", cung: ["Điền Trạch", "Phụ Mẫu", "Phu Thê", "Thiên Di"], yeuToThem: "Lộc Tồn, Hóa Lộc, Đường Phù; Không Kiếp, Hóa Kỵ tại Điền Trạch; Thiên Mã, Phá Quân tại Điền Trạch; đại vận đi qua Điền Trạch", van: ["chuoi"], khongDuoc: "Không tư vấn tài chính", chiTiet: "Năm cụ thể — nêu khi nguồn có luật năm và điều kiện khớp", cungChinh: "Điền Trạch", tuKhoa: "nha-cua" },
  // tinh-duyen — gộp TD03+TD04+TD05 / TD06 / TD01+TD02+TD07+TD08
  { id: "TD01", thoiDiem: "khong", loai: "chuyen-sau", chuDe: "tinh-duyen", cauHoi: "Người bạn đời của tôi là người thế nào?", nhanDuoc: "Chân dung người đi cùng: tính cách, năng lực, công việc, nền tảng, khí chất; kiểu người thu hút mình và kiểu thật sự hợp lâu dài có giống nhau không; dễ gặp người ấy trong hoàn cảnh nào", yBatBuoc: "Chân dung + Thu hút và hợp lâu dài + Hoàn cảnh gặp", cung: ["Phu Thê", "Mệnh", "Thiên Di", "Quan Lộc"], yeuToThem: "Chính tinh và phụ tinh tại Phu Thê; xung Quan Lộc; Đào Hoa, Hồng Loan, Thiên Riêu, Mộc Dục; Thiên Mã", van: [], khongDuoc: "", chiTiet: "Hơn hay kém tuổi, nghề, dáng người, gần hay xa quê — nêu khi nguồn nói rõ cho đúng tổ hợp" },
  { id: "TD02", thoiDiem: "co", loai: "chuyen-sau", chuDe: "tinh-duyen", cauHoi: "Duyên của tôi đến sớm hay muộn, lúc nào thuận để gắn bó lâu dài?", nhanDuoc: "Duyên đến sớm hay muộn (theo TRẠNG THÁI DUYÊN trong dữ kiện); khoảng tuổi có cửa gắn bó lâu dài — kết hôn nếu người đọc muốn; dễ yêu lâu mới về chung không; có lỡ một cửa rồi đến cửa khác không", yBatBuoc: "Đáp + Khi nào", cung: [], yeuToThem: "Tuần/Triệt tại Phu Thê; lưu Hồng Loan, Thiên Hỷ, Đào Hoa", van: ["chuoi", "th3"], khongDuoc: "Không phán ngày cưới; không mặc định người đọc chắc chắn sẽ kết hôn", chiTiet: "Năm cụ thể — nêu khi nguồn có luật năm cưới và điều kiện khớp dữ kiện" },
  { id: "TD03", thoiDiem: "khong", loai: "chuyen-sau", chuDe: "tinh-duyen", cauHoi: "Tôi yêu thế nào, và chuyện gắn bó lâu dài dễ vấp ở đâu?", nhanDuoc: "Kiểu yêu (chủ động hay bị động, sâu hay nông, chiếm hữu, lý trí, dễ hy sinh, dễ rút lui) và nó dẫn tới chuyện gì; thử thách chính khi gắn bó lâu dài (tiền, gia đình, xa cách, sự nghiệp, tính cách, người thứ ba, con cái); xu hướng ổn định hay biến động; bạn đời đổi đời mình ở mặt nào", yBatBuoc: "Kiểu yêu + Thử thách chính + Xu hướng", cung: ["Phu Thê", "Mệnh", "Phúc Đức", "Quan Lộc"], yeuToThem: "Sao đào hoa tại Mệnh, Phúc Đức; Tham Lang, Liêm Trinh; sát tinh, Hóa Kỵ, Cô Thần, Quả Tú tại Phu Thê; Lộc Tồn, Hóa Lộc tại Phu Thê", van: [], khongDuoc: "Không khẳng định chia tay, ly hôn hay ngoại tình — chỉ nói xu hướng và điều kiện" },
  // con-cai — gộp CC01+CC02 / CC03+CC04 / CC05+CC06
  { id: "CC01", thoiDiem: "phu", loai: "chuyen-sau", chuDe: "con-cai", cauHoi: "Đường con cái của tôi thế nào: ít hay đông, sớm hay muộn?", nhanDuoc: "Duyên con thuận hay cần thời gian, cần chăm lo; xu hướng ít hay đông con; con đến sớm hay muộn và khoảng thời gian thuận", yBatBuoc: "Đáp + Ít hay đông + Khi nào", cung: [], yeuToThem: "Chính tinh, sát tinh tại Tử Tức; Thai, Dưỡng; Tuần/Triệt tại Tử Tức; đại vận đi qua Tử Tức", van: ["chuoi"], khongDuoc: "", chiTiet: "Số con, con trai hay con gái, con đầu lòng — nêu khi nguồn nói rõ và điều kiện khớp lá số" },
  { id: "CC02", thoiDiem: "khong", loai: "chuyen-sau", chuDe: "con-cai", cauHoi: "Con của tôi (nếu có) là đứa trẻ thế nào, có hợp với tôi không?", nhanDuoc: "Khí chất và tiềm năng của con (cá tính, độc lập, học hành, gần hay xa nhà); quan hệ cha mẹ – con gần gũi hay có lúc xa cách, lúc con nhỏ và khi con trưởng thành", yBatBuoc: "Chân dung xu hướng + Quan hệ", cung: ["Tử Tức", "Mệnh"], yeuToThem: "Chính tinh Tử Tức; không có chính tinh thì mượn Điền Trạch", van: [], khongDuoc: "" },
  { id: "CC03", thoiDiem: "khong", loai: "chuyen-sau", chuDe: "con-cai", cauHoi: "Về sau tôi có nhờ được con không?", nhanDuoc: "Mức và kiểu nâng đỡ của con về sau; con cái đổi đời mình ở mặt nào (tiền, sự nghiệp, nơi ở, hôn nhân, ưu tiên sống)", yBatBuoc: "Đáp + Kiểu nâng đỡ", cung: ["Tử Tức", "Điền Trạch", "Mệnh"], yeuToThem: "Đại vận cuối", van: [], khongDuoc: "" },
  // gia-dinh — gộp GD01–05 / anh-em / phuc-duc
  { id: "GD01", thoiDiem: "khong", loai: "chuyen-sau", chuDe: "gia-dinh", cauHoi: "Gia đình là chỗ dựa hay gánh nặng của tôi?", nhanDuoc: "Nền tảng gia đình gốc (ổn định hay biến động, vật chất, nề nếp); được đỡ phần nào (tiền, học, nhà, quan hệ) và phần nào tự thân; quan hệ với cha và với mẹ khác nhau thế nào; về sau có phải gánh nhiều trách nhiệm với cha mẹ không", yBatBuoc: "Nền tảng + Được đỡ và tự thân + Cha và mẹ", cung: ["Phụ Mẫu", "Phúc Đức", "Điền Trạch", "Mệnh"], yeuToThem: "Chính tinh Phụ Mẫu; Âm Dương thuận lý; Thái Dương (cha), Thái Âm (mẹ) theo độ sáng; Hóa Khoa, Ân Quang, Thiên Quý tại Phụ Mẫu", van: [], khongDuoc: "Không bịa nghề của cha mẹ khi không có nguồn; không luận sinh tử cha mẹ" },
  { id: "GD02", thoiDiem: "khong", loai: "chuyen-sau", chuDe: "gia-dinh", cauHoi: "Anh chị em của tôi giúp nhau hay vướng nhau?", nhanDuoc: "Hòa thuận / xa cách / nhiều va chạm; ai hay là người gánh; lúc có chuyện lớn có giúp được nhau không; tiền bạc, tài sản chung dễ nảy mâu thuẫn không, có nên làm ăn chung", yBatBuoc: "Kiểu quan hệ + Mức giúp + Chỗ dễ vướng", cung: ["Huynh Đệ", "Nô Bộc", "Tài Bạch"], yeuToThem: "Chính tinh, sát tinh tại Huynh Đệ; Huynh Đệ không có chính tinh thì mượn Nô Bộc; Không Kiếp, Kình Đà, Hóa Kỵ tại Huynh Đệ", van: [], khongDuoc: "", chiTiet: "Số anh chị em, mình là con thứ mấy — nêu khi nguồn nói rõ", cungChinh: "Huynh Đệ", tuKhoa: "anh-em" },
  { id: "GD03", thoiDiem: "phu", loai: "chuyen-sau", chuDe: "gia-dinh", cauHoi: "Phúc đức và hậu vận của tôi thế nào?", nhanDuoc: "Nền phúc dòng họ ảnh hưởng đời mình mạnh đến đâu; gặp khó có hay có đường thoát; điều gì trong đời thường \"được cứu\", điều gì dễ thành gánh; càng về sau đời nhẹ đi hay vẫn bôn ba, hậu vận thiên về điều gì", yBatBuoc: "Nền phúc + Đường thoát + Hậu vận", cung: ["Phúc Đức", "THAN", "Mệnh"], yeuToThem: "Chính tinh, sát tinh tại Phúc Đức; Thiên Đức, Nguyệt Đức; Giải Thần, Thiên Giải, Thiên Quan, Thiên Phúc", van: ["chuoi"], khongDuoc: "KHÔNG luận thọ yểu; không sáng tác lịch sử dòng họ", cungChinh: "Phúc Đức", tuKhoa: "phuc-duc" },
  // suc-khoe — gộp SK01–SK04 / SK05+SK06
  { id: "SK01", thoiDiem: "khong", loai: "chuyen-sau", chuDe: "suc-khoe", cauHoi: "Sức khỏe của tôi cần lưu ý gì?", nhanDuoc: "Thể trạng chung (bền hay dễ suy, hồi phục nhanh hay chậm); 2–3 nhóm cơ quan / vùng đáng lưu ý hơn cả, XẾP theo mức đáng lưu ý, kèm căn cứ; vấn đề nếu có thường âm ỉ, tái phát hay đột ngột; nguy cơ thương tích chỉ nói khi tín hiệu rõ", yBatBuoc: "Thể trạng + Xếp hạng nhóm đáng lưu ý + Kiểu vấn đề", cung: ["Tật Ách", "Mệnh", "Phúc Đức"], yeuToThem: "Chính tinh Tật Ách; ngũ hành Mệnh – Cục; ngũ hành của chính tinh và sát tinh tại Tật Ách (Hỏa – tim mạch, huyết áp; Thủy – thận, tiết niệu; Mộc – gan mật; Kim – hô hấp; Thổ – tiêu hóa) theo quan niệm truyền thống; Đà La, Hóa Kỵ (âm ỉ); Kình Dương, Hỏa Tinh (đột ngột); Thiên Hình, Linh Tinh, Lưu Hà", van: [], khongDuoc: "Nói là xu hướng đáng chú ý hơn, không khẳng định sẽ mắc, không chẩn đoán; không dọa — tín hiệu yếu thì nói là yếu", chiTiet: "Bộ phận cụ thể (dạ dày, huyết áp, cột sống…) — nêu khi nguồn nói rõ cho đúng tổ hợp" },
  { id: "SK02", thoiDiem: "co", loai: "chuyen-sau", chuDe: "suc-khoe", cauHoi: "Giai đoạn nào tôi cần giữ sức hơn?", nhanDuoc: "Các giai đoạn cần theo dõi kỹ và vì sao; riêng năm nay có điểm nào đáng lưu ý", yBatBuoc: "Dòng thời gian + Năm nay", cung: ["Tật Ách", "TH"], yeuToThem: "Đại vận, tiểu hạn đi qua Tật Ách hoặc gặp sát tinh, Hóa Kỵ, Bạch Hổ, Thiên Hình; lưu tứ hóa, lưu sát tinh vào Tật Ách", van: ["chuoi", "th"], khongDuoc: "", chiTiet: "Tháng hoặc năm cụ thể — nêu khi nguồn có luật và điều kiện khớp" },
  // ra-ngoai — gộp RN02–04+HV05 / RN01+RN05+RN06
  { id: "RN01", thoiDiem: "phu", loai: "chuyen-sau", chuDe: "ra-ngoai", cauHoi: "Tôi có duyên đi xa, xuất ngoại không?", nhanDuoc: "Mức duyên đi xa trong nước và ra nước ngoài (học, làm, sống); điều gì dễ đưa mình đi; đi xa có thật sự làm vận tốt lên không; giai đoạn dễ đi", yBatBuoc: "Mức duyên + Lý do đi + Có phát không", cung: ["Thiên Di", "Mệnh", "Quan Lộc"], yeuToThem: "Thiên Mã, Lộc Tồn (Lộc Mã); sát tinh ở Thiên Di; Hóa Khoa ở Thiên Di (học xa)", van: ["chuoi"], khongDuoc: "", chiTiet: "Năm đi, hướng hay vùng đất hợp — nêu khi nguồn nói rõ" },
  { id: "RN02", thoiDiem: "khong", loai: "chuyen-sau", chuDe: "ra-ngoai", cauHoi: "Ra ngoài tôi có hơn ở quê không, định cư hay trở về?", nhanDuoc: "So vận khi ra xã hội với khi ở chỗ quen; ra ngoài dễ gặp quý nhân hay thị phi; lâu dài định cư nơi khác hay quay về", yBatBuoc: "So sánh + Cơ hội và rủi ro + Kết cục", cung: ["Thiên Di", "Mệnh", "Điền Trạch"], yeuToThem: "Chính tinh Thiên Di; Tả Hữu, Khôi Việt; Lưu Hà, Thiên Hình, sát tinh tại Thiên Di", van: [], khongDuoc: "Không dọa tai nạn" },
  // van-han — gộp VH01+VH02 / VH03+VH04 / VH05–VH08
  { id: "VH01", thoiDiem: "co", loai: "chuyen-sau", chuDe: "van-han", cauHoi: "Các chặng đời của tôi: khi nào lên, khi nào chững?", nhanDuoc: "Mạch các chặng đời (tiền vận, trung vận, hậu vận) — chỉ nêu chặng có tín hiệu rõ trong dữ kiện vận; những bước ngoặt lớn nhất; mỗi chặng: chủ đề, cơ hội, rủi ro — KHÔNG bắt đầu bằng bảng mười năm", yBatBuoc: "Mạch chặng đời + Bước ngoặt + Từng chặng", cung: ["Mệnh"], yeuToThem: "Tam phương mỗi cung vận so với nguyên cục", van: ["chuoi"], khongDuoc: "" },
  { id: "VH02", thoiDiem: "co", loai: "chuyen-sau", chuDe: "van-han", cauHoi: "Mười năm này tôi nên tập trung vào điều gì?", nhanDuoc: "Chặng hiện tại thiên về mở rộng / thay đổi / tích lũy / thử thách / thu hoạch, vì sao; những việc lớn dễ xảy ra trong chặng này (việc, tiền, cưới, con, nhà, đi xa, sức khỏe) — chọn tín hiệu mạnh nhất", yBatBuoc: "Chặng hiện tại + Việc lớn dễ xảy ra + Trọng tâm", cung: ["DV"], yeuToThem: "Tam phương cung vận; sao nguyên cục tại cung vận; lưu tứ hóa các năm trong vận", van: ["dv"], khongDuoc: "" },
  { id: "VH03", thoiDiem: "co", loai: "chuyen-sau", chuDe: "van-han", cauHoi: "Năm nay và ba năm tới của tôi thế nào?", nhanDuoc: "Chủ đề năm nay + cơ hội lớn nhất, rủi ro lớn nhất; lĩnh vực nào dễ biến động; quãng nào trong năm nổi bật khi dữ kiện nguyệt hạn chỉ rõ; ba năm tới nối thành một mạch (năm trước mở ra gì, năm sau tiếp thế nào) — chỉ nối khi dữ kiện từng năm cho phép, không dựng chuyện, cũng không phải ba lời bói rời", yBatBuoc: "Chủ đề năm + Cơ hội và rủi ro + Mạch ba năm", cung: ["TH"], yeuToThem: "Lưu Thái Tuế; lưu tứ hóa theo can năm; nguyệt hạn đếm từ tiểu hạn; đối chiếu đại vận", van: ["th", "nguyet", "th3", "dv"], khongDuoc: "", chiTiet: "Tháng nổi bật trong năm — nêu khi nguồn hoặc dữ kiện nguyệt hạn chỉ rõ" },
];
