/**
 * KHUNG CÂU HỎI v3 — sinh tự động từ KHUNG-LUAN-GIAI-v3.xlsx (sheet 1, 2, 3) mà
 * chủ dự án đã duyệt ngày 23/09/2026. Đừng sửa câu chữ ở đây bằng tay: sửa trong
 * khung rồi sinh lại, không thì hai bản lệch nhau mà không ai biết bản nào đúng.
 *
 * Token cung đặc biệt: "THAN" = cung an Thân, "DV" = cung đại vận đang chạy,
 * "TH" = cung tiểu hạn của năm xem.
 */

export type LopVan = 'dv' | 'chuoi' | 'th' | 'th3' | 'nguyet' | 'diem';

export interface ChuDeV3 {
  ma: string;
  id: string;
  ten: string;
  cungChinh: string;
  phuTro: { cung: string; vaiTro: string }[];
  saoToanCuc: string;
}

export interface CauHoiV3 {
  id: string;
  loai: 'tong-quan' | 'chuyen-sau';
  chuDe: string;
  cauHoi: string;
  nhanDuoc: string;
  /** Những ý bài phải có — lấy từ cột "Ý bắt buộc phải có" / "Cung & yếu tố" */
  yBatBuoc: string;
  /** Cung phải đọc, theo thứ tự ưu tiên. Rỗng = cung chính của chủ đề + tam phương */
  cung: string[];
  yeuToThem: string;
  van: LopVan[];
  khongDuoc: string;
}

export const PHIEN_BAN_KHUNG_V3 = '2026.09.1';

export const CHU_DE_V3: ChuDeV3[] = [
  { ma: "TC", id: "tinh-cach", ten: "Tính cách & con người", cungChinh: "Mệnh", phuTro: [{"cung": "Thân", "vaiTro": "con người từ khoảng 30 tuổi trở đi; nặng dần theo tuổi"}, {"cung": "Tật Ách", "vaiTro": "\"mệnh thứ hai\": nét tính cách ẩn, bản năng, phản ứng khi áp lực, thể chất"}, {"cung": "Phúc Đức", "vaiTro": "tư tưởng, đời sống tinh thần, cách hưởng thụ"}], saoToanCuc: "Chính tinh tại Mệnh + độ sáng; cách cục của tam phương Mệnh; Mệnh chủ, Thân chủ; ngũ hành bản mệnh – Cục; vòng Tràng Sinh tại Mệnh; Tuần/Triệt tại Mệnh" },
  { ma: "SN", id: "su-nghiep", ten: "Sự nghiệp", cungChinh: "Quan Lộc", phuTro: [{"cung": "Thiên Di", "vaiTro": "môi trường bên ngoài, cơ hội nơi xa"}, {"cung": "Nô Bộc", "vaiTro": "đồng nghiệp, cấp dưới, khách hàng"}, {"cung": "Phụ Mẫu", "vaiTro": "cấp trên, cơ quan nhà nước, giấy tờ, học vấn"}, {"cung": "Điền Trạch", "vaiTro": "nơi làm việc, cơ sở kinh doanh"}], saoToanCuc: "Hóa Quyền, Hóa Khoa; Khôi Việt, Tả Hữu; Xương Khúc; Thiên Mã; Quốc Ấn, Thai Phụ, Phong Cáo; Lộc Tồn" },
  { ma: "TB", id: "tien-bac", ten: "Tiền bạc", cungChinh: "Tài Bạch", phuTro: [{"cung": "Điền Trạch", "vaiTro": "kho của: giữ tiền, tài sản, bất động sản"}, {"cung": "Thiên Di", "vaiTro": "tiền từ bên ngoài, nơi xa"}, {"cung": "Nô Bộc", "vaiTro": "tiền qua người khác: khách hàng, cấp dưới"}, {"cung": "Huynh Đệ", "vaiTro": "hùn vốn, vay mượn người thân"}, {"cung": "Phu Thê", "vaiTro": "bạn đời tác động tới tiền"}, {"cung": "Tử Tức", "vaiTro": "hợp tác, đầu tư [theo một số trường phái — cần kiểm]"}], saoToanCuc: "Lộc Tồn, Hóa Lộc (vị trí trên cả lá); Địa Không, Địa Kiếp; Đại Hao, Tiểu Hao; Hóa Kỵ; Hỏa Tinh, Linh Tinh (tiền đột phát)" },
  { ma: "TD", id: "tinh-duyen", ten: "Tình duyên & hôn nhân", cungChinh: "Phu Thê", phuTro: [{"cung": "Mệnh / Thân", "vaiTro": "bản thân mình trong hôn nhân"}, {"cung": "Tử Tức", "vaiTro": "đời sống vợ chồng, chuyện chăn gối"}, {"cung": "Điền Trạch", "vaiTro": "tổ ấm, đời sống chung"}], saoToanCuc: "Sao đào hoa trên cả lá: Đào Hoa, Hồng Loan, Thiên Hỷ, Thiên Riêu, Hàm Trì, Mộc Dục; Cô Thần, Quả Tú; Tuần/Triệt tại Phu Thê" },
  { ma: "CC", id: "con-cai", ten: "Con cái", cungChinh: "Tử Tức", phuTro: [{"cung": "Phu Thê", "vaiTro": "vợ chồng ảnh hưởng tới con"}, {"cung": "Phúc Đức", "vaiTro": "phúc để lại cho con"}, {"cung": "Mệnh", "vaiTro": "cách mình làm cha mẹ"}], saoToanCuc: "Thai, Dưỡng (vòng Tràng Sinh); sát tinh và Tuần/Triệt tại Tử Tức — KHÔNG luận số con, giới tính" },
  { ma: "GD", id: "gia-dinh", ten: "Cha mẹ & gia đình gốc", cungChinh: "Phụ Mẫu", phuTro: [{"cung": "Phúc Đức", "vaiTro": "dòng họ, tổ tiên"}, {"cung": "Mệnh", "vaiTro": "mình trong mắt cha mẹ"}, {"cung": "Thái Dương / Thái Âm", "vaiTro": "vị trí và độ sáng: cha / mẹ (bất kể nằm ở cung nào)"}], saoToanCuc: "Âm Dương thuận lý hay nghịch lý; Hóa Khoa; Ân Quang, Thiên Quý; Tang Môn, Bạch Hổ, Điếu Khách" },
  { ma: "AE", id: "anh-em", ten: "Anh chị em", cungChinh: "Huynh Đệ", phuTro: [{"cung": "Nô Bộc", "vaiTro": "đối cung: người ngoài so với người nhà"}], saoToanCuc: "Sát tinh, Không Kiếp tại Huynh Đệ; cung không có chính tinh thì mượn chính tinh của Nô Bộc" },
  { ma: "QN", id: "quy-nhan", ten: "Bạn bè, cộng sự, quý nhân", cungChinh: "Nô Bộc", phuTro: [{"cung": "Thiên Di", "vaiTro": "người gặp ngoài xã hội"}, {"cung": "Phụ Mẫu", "vaiTro": "người trên nâng đỡ"}], saoToanCuc: "Quý nhân tinh trên cả lá: Khôi Việt, Tả Hữu, Thiên Quan, Thiên Phúc, Ân Quang, Thiên Quý, Hóa Khoa" },
  { ma: "PD", id: "phuc-duc", ten: "Phúc đức & đời sống tinh thần", cungChinh: "Phúc Đức", phuTro: [{"cung": "Phụ Mẫu", "vaiTro": "cha mẹ, bề trên"}, {"cung": "Điền Trạch", "vaiTro": "tổ nghiệp"}, {"cung": "Mệnh", "vaiTro": "phần mình tự tạo"}], saoToanCuc: "Thiên Đức, Nguyệt Đức, Long Đức, Phúc Đức (vòng Thái Tuế); Thiên Quan, Thiên Phúc; Hóa Lộc/Hóa Kỵ tại Phúc Đức" },
  { ma: "SK", id: "suc-khoe", ten: "Sức khỏe", cungChinh: "Tật Ách", phuTro: [{"cung": "Mệnh / Thân", "vaiTro": "thể chất gốc"}, {"cung": "Phúc Đức", "vaiTro": "sức bền, tinh thần"}, {"cung": "Ngũ hành bản mệnh – Cục", "vaiTro": "nền thể trạng"}], saoToanCuc: "Kình Dương, Đà La, Hỏa Tinh, Linh Tinh, Địa Không, Địa Kiếp; Hóa Kỵ; Thiên Hình; Bệnh Phù — chỉ luận XU HƯỚNG, không chẩn đoán" },
  { ma: "NC", id: "nha-cua", ten: "Nhà cửa & tài sản", cungChinh: "Điền Trạch", phuTro: [{"cung": "Tài Bạch", "vaiTro": "sức tài chính để mua, giữ"}, {"cung": "Phụ Mẫu", "vaiTro": "thừa kế"}, {"cung": "Thiên Di", "vaiTro": "chuyển chỗ ở, nơi xa"}], saoToanCuc: "Lộc Tồn, Hóa Lộc, Đường Phù; Địa Không, Địa Kiếp, Đại Hao; Hóa Kỵ (giấy tờ, tranh chấp)" },
  { ma: "RN", id: "ra-ngoai", ten: "Ra ngoài, đi xa, môi trường", cungChinh: "Thiên Di", phuTro: [{"cung": "Mệnh", "vaiTro": "đối chiếu: mình ở nhà và mình ở ngoài"}], saoToanCuc: "Thiên Mã, Lộc Tồn (Lộc Mã); Tả Hữu, Khôi Việt; sát tinh; Lưu Hà, Thiên Hình (an toàn đi lại)" },
  { ma: "HV", id: "hoc-van", ten: "Học vấn & bằng cấp", cungChinh: "Quan Lộc", phuTro: [{"cung": "Phụ Mẫu", "vaiTro": "văn thư, thi cử, thầy"}, {"cung": "Mệnh", "vaiTro": "tư chất học"}], saoToanCuc: "Văn Xương, Văn Khúc, Khôi Việt, Hóa Khoa, Long Trì, Phượng Các, Tấu Thư, Bác Sĩ, LN Văn Tinh" },
  { ma: "VH", id: "van-han", ten: "Vận hạn", cungChinh: "Cung đại vận / tiểu hạn", phuTro: [{"cung": "Nguyên cục", "vaiTro": "vận chỉ kích hoạt cái vốn có; luôn đối chiếu với cung gốc cùng chủ đề"}], saoToanCuc: "Tam phương tứ chính của cung vận; lưu Thái Tuế; lưu tứ hóa theo can năm; lưu Lộc Tồn, lưu Kình Đà; nguyệt hạn (tùy chọn)" },
];

export const CAU_HOI_V3: CauHoiV3[] = [
  { id: "TQ01", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Tôi là người như thế nào?", nhanDuoc: "Một câu định danh + một câu về mặt bên trong", yBatBuoc: "Mệnh (chính) + tam hợp Tài Bạch, Quan Lộc + xung Thiên Di; Thân; Tật Ách, Phúc Đức cho mặt bên trong", cung: ["Mệnh", "THAN", "Tật Ách", "Phúc Đức"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "TQ02", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Điểm mạnh nổi bật nhất của tôi?", nhanDuoc: "Một năng lực + một lợi thế trong đời", yBatBuoc: "Cách cục cát mạnh nhất; cung có chính tinh miếu vượng + cát tinh; vị trí Hóa Lộc / Quyền / Khoa", cung: ["Mệnh", "Quan Lộc", "Tài Bạch"], yeuToThem: "", van: ["diem"], khongDuoc: "" },
  { id: "TQ03", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Điều tôi cần lưu ý nhất?", nhanDuoc: "Một kiểu sai lặp lại hoặc một mặt yếu của đời", yBatBuoc: "Cung yếu nhất (chính tinh hãm + sát tinh + Hóa Kỵ); sát tinh ở Mệnh, Thân, Phúc Đức", cung: ["Mệnh", "Phúc Đức"], yeuToThem: "", van: ["diem"], khongDuoc: "" },
  { id: "TQ04", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Lá số mạnh ở mặt nào, yếu ở mặt nào?", nhanDuoc: "Xếp 12 mặt đời vào 3 nhóm Mạnh / Bình / Cần gắng", yBatBuoc: "Chấm từng cung theo luật: chính tinh + độ sáng + cát/sát tinh + tứ hóa + Tuần/Triệt (engine chấm, không dùng LLM)", cung: ["Mệnh"], yeuToThem: "", van: ["diem"], khongDuoc: "" },
  { id: "TQ05", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Tôi hợp hướng nghề nào?", nhanDuoc: "Một dòng: nhóm nghề + vai trò", yBatBuoc: "Quan Lộc + tam phương", cung: ["Quan Lộc"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "TQ06", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Tiền bạc của tôi nói chung thế nào?", nhanDuoc: "Mức kiếm / mức giữ + nguồn chính", yBatBuoc: "Tài Bạch + tam phương + Phúc Đức (xung) + Điền Trạch", cung: ["Tài Bạch", "Phúc Đức", "Điền Trạch"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "TQ07", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Tình duyên của tôi nói chung thế nào?", nhanDuoc: "Kiểu duyên + sớm hay muộn", yBatBuoc: "Phu Thê + tam phương", cung: ["Phu Thê"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "TQ08", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Giai đoạn 10 năm hiện tại của tôi là giai đoạn gì?", nhanDuoc: "Tên giai đoạn + chủ đề + 1 lưu ý", yBatBuoc: "Cung đại vận hiện tại + tam phương, đặt lên nguyên cục", cung: ["DV"], yeuToThem: "", van: ["dv"], khongDuoc: "" },
  { id: "TQ09", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Năm nay tôi cần biết gì?", nhanDuoc: "Chủ đề năm + nên / tránh", yBatBuoc: "Tiểu hạn + lưu Thái Tuế + lưu tứ hóa + đại vận", cung: ["TH"], yeuToThem: "", van: ["th", "dv"], khongDuoc: "" },
  { id: "TQ10", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Đường đời của tôi đi lên thế nào (tiền vận – trung vận – hậu vận)?", nhanDuoc: "Mỗi giai đoạn 10 năm 1 dòng", yBatBuoc: "Tất cả cung đại vận; Mệnh (tiền vận) vs Thân (hậu vận); Triệt (tiền vận), Tuần (hậu vận)", cung: ["Mệnh", "THAN"], yeuToThem: "", van: ["chuoi"], khongDuoc: "" },
  { id: "TQ11", loai: "tong-quan", chuDe: "tong-quan", cauHoi: "Tôi nên xem sâu phần nào trước?", nhanDuoc: "2–3 chủ đề + lý do 1 dòng (sinh theo luật, không phải luận giải)", yBatBuoc: "Điểm mạnh / yếu (TQ04) + đại vận hiện tại + độ nổi bật", cung: ["Mệnh"], yeuToThem: "", van: ["diem", "dv", "chuoi"], khongDuoc: "" },
  { id: "TC01", loai: "chuyen-sau", chuDe: "tinh-cach", cauHoi: "Bản chất tôi là người như thế nào?", nhanDuoc: "Một câu định danh + 3–5 nét hành vi nhận ra được trong đời thường", yBatBuoc: "Đáp + Cụ thể + Cần biết", cung: [], yeuToThem: "Chính tinh Mệnh + độ sáng; cách cục; phụ tinh tại Mệnh; Mệnh không có chính tinh thì mượn Thiên Di", van: [], khongDuoc: "Không liệt kê nghĩa từng sao; không viết câu đúng với ai cũng được" },
  { id: "TC02", loai: "chuyen-sau", chuDe: "tinh-cach", cauHoi: "Điểm mạnh thật sự của tôi là gì?", nhanDuoc: "3 điểm mạnh + nơi dùng được điểm mạnh đó", yBatBuoc: "Danh sách 3 + Cần biết", cung: [], yeuToThem: "Cát tinh trong tam phương Mệnh: Tả Hữu, Khôi Việt, Xương Khúc, Lộc Tồn, Hóa Lộc/Quyền/Khoa", van: [], khongDuoc: "Không khen chung chung" },
  { id: "TC03", loai: "chuyen-sau", chuDe: "tinh-cach", cauHoi: "Điểm yếu, thói quen dễ hại tôi là gì?", nhanDuoc: "2–3 điểm yếu + dấu hiệu tự nhận ra", yBatBuoc: "Danh sách + Dấu hiệu", cung: ["Mệnh", "Tật Ách", "Phúc Đức"], yeuToThem: "Sát tinh (Kình, Đà, Hỏa, Linh, Không, Kiếp), Hóa Kỵ, chính tinh hãm", van: [], khongDuoc: "Không dọa, không gắn nhãn xấu" },
  { id: "TC04", loai: "chuyen-sau", chuDe: "tinh-cach", cauHoi: "Con người bên trong tôi ra sao? Khi áp lực tôi phản ứng thế nào?", nhanDuoc: "Mặt ẩn ít người thấy + phản ứng khi áp lực + cách xả hợp", yBatBuoc: "Đáp + Cụ thể + Cần biết", cung: ["Tật Ách", "Phúc Đức", "Mệnh"], yeuToThem: "Tật Ách = mệnh thứ hai (bản năng); Phúc Đức = tinh thần; so với Mệnh để chỉ ra độ vênh trong – ngoài", van: ["dv"], khongDuoc: "Không luận bệnh ở câu này" },
  { id: "TC05", loai: "chuyen-sau", chuDe: "tinh-cach", cauHoi: "Người khác nhìn tôi thế nào, có khác con người thật không?", nhanDuoc: "Ấn tượng bên ngoài vs con người thật + hiểu nhầm hay gặp", yBatBuoc: "Đáp + Cụ thể", cung: ["Thiên Di", "Mệnh"], yeuToThem: "Chính tinh Thiên Di; Tả Hữu, Khôi Việt; sát tinh ở Thiên Di", van: [], khongDuoc: "" },
  { id: "TC06", loai: "chuyen-sau", chuDe: "tinh-cach", cauHoi: "Tôi ra quyết định theo kiểu nào?", nhanDuoc: "Kiểu quyết định + điểm mù + lúc dễ quyết sai", yBatBuoc: "Đáp + Cụ thể + Cần biết", cung: ["Mệnh", "Quan Lộc", "Tài Bạch"], yeuToThem: "Hóa Kỵ, Hóa Quyền; Thiên Cơ, Cự Môn (suy tính); Thất Sát, Phá Quân (quyết nhanh)", van: [], khongDuoc: "" },
  { id: "TC07", loai: "chuyen-sau", chuDe: "tinh-cach", cauHoi: "Tôi sẽ thay đổi thế nào theo tuổi?", nhanDuoc: "Tiền vận vs hậu vận: tôi của tuổi trẻ và tôi của về sau", yBatBuoc: "Hai mốc + 1 câu mỗi mốc", cung: ["Mệnh", "THAN"], yeuToThem: "Cung Thân (nặng dần sau khoảng 30); Tuần (hậu vận) / Triệt (tiền vận) tại Mệnh, Thân", van: ["chuoi"], khongDuoc: "" },
  { id: "SN01", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Tôi hợp ngành nghề, lĩnh vực nào?", nhanDuoc: "4–6 nhóm nghề hợp + 2–3 nhóm không hợp, có tên nghề cụ thể", yBatBuoc: "Danh sách Hợp / Không hợp + Cần biết", cung: [], yeuToThem: "Bảng tri thức sao → nghề (chờ chuyên gia duyệt); Xương Khúc (chữ nghĩa), Vũ Khúc (tài chính), Thiên Mã (di chuyển), Hóa Quyền; ngũ hành Mệnh chỉ để tham khảo", van: [], khongDuoc: "Không liệt kê quá 6 nhóm; không đưa nghề mà không có căn cứ" },
  { id: "SN02", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Tôi hợp vai trò nào: chuyên môn, quản lý, kinh doanh, sáng tạo hay hỗ trợ?", nhanDuoc: "1 vai trò chính + 1 vai trò phụ + vì sao", yBatBuoc: "Đáp + Cụ thể", cung: ["Quan Lộc", "Mệnh"], yeuToThem: "Tử Vi, Thiên Phủ, Thiên Tướng (quản lý); Thất Sát, Phá Quân (tiên phong); Cơ Nguyệt Đồng Lương (chuyên môn, hỗ trợ); Cự Môn (dùng lời nói); Tham Lang (giao tế)", van: [], khongDuoc: "" },
  { id: "SN03", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Tôi nên làm công, làm tự do hay kinh doanh riêng?", nhanDuoc: "Đáp án + điều kiện + giai đoạn phù hợp", yBatBuoc: "Đáp có điều kiện + Khi nào", cung: ["Quan Lộc", "Tài Bạch", "Mệnh", "Nô Bộc", "Huynh Đệ", "Thiên Di"], yeuToThem: "Thêm Nô Bộc (khách, cấp dưới), Huynh Đệ (hùn), Thiên Di (thị trường ngoài)", van: ["chuoi"], khongDuoc: "Không khẳng định chắc chắn thành hay bại" },
  { id: "SN04", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Môi trường làm việc nào hợp với tôi?", nhanDuoc: "Loại tổ chức (nhà nước / tư nhân / nước ngoài / khởi nghiệp), quy mô, văn hóa", yBatBuoc: "Hợp / Không hợp", cung: ["Quan Lộc", "Thiên Di", "Phụ Mẫu"], yeuToThem: "Phụ Mẫu tốt → hợp tổ chức có cấp trên rõ; Thiên Di mạnh → hợp môi trường ngoài, nơi xa", van: [], khongDuoc: "" },
  { id: "SN05", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Quan hệ với cấp trên, đồng nghiệp, cấp dưới thế nào?", nhanDuoc: "3 dòng: cấp trên / ngang hàng / cấp dưới", yBatBuoc: "3 dòng", cung: ["Phụ Mẫu", "Huynh Đệ", "Nô Bộc"], yeuToThem: "Phụ Mẫu = cấp trên; Huynh Đệ = ngang hàng; Nô Bộc = cấp dưới, khách", van: [], khongDuoc: "" },
  { id: "SN06", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Lộ trình thăng tiến của tôi ra sao, đỉnh ở giai đoạn nào?", nhanDuoc: "Con đường đi lên + các mốc giai đoạn + giai đoạn đỉnh", yBatBuoc: "Đáp + Khi nào (bảng mốc) + Cần biết", cung: [], yeuToThem: "Hóa Quyền, Khôi Việt, Quốc Ấn, Thai Phụ, Phong Cáo", van: ["chuoi"], khongDuoc: "Không nêu chức danh cụ thể như sự thật" },
  { id: "SN07", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Giai đoạn hiện tại, sự nghiệp nên tiến, giữ hay chuyển?", nhanDuoc: "Tiến / Giữ / Chuyển + điều kiện + dấu hiệu nên dừng", yBatBuoc: "Đáp + Điều kiện", cung: ["DV", "Quan Lộc"], yeuToThem: "Tam phương cung vận; tiểu hạn năm nay; lưu tứ hóa", van: ["dv", "th"], khongDuoc: "" },
  { id: "SN08", loai: "chuyen-sau", chuDe: "su-nghiep", cauHoi: "Tôi có hợp làm việc xa quê, nước ngoài không?", nhanDuoc: "Hợp / Không + kiểu đi (công tác, định cư, làm việc từ xa)", yBatBuoc: "Đáp + Cụ thể", cung: ["Thiên Di", "Quan Lộc"], yeuToThem: "Thiên Mã, Lộc Tồn (Lộc Mã); sát tinh ở Thiên Di", van: ["chuoi"], khongDuoc: "" },
  { id: "TB01", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Tiền của tôi đến từ những nguồn nào?", nhanDuoc: "Nguồn chính + nguồn phụ, gọi tên được", yBatBuoc: "Danh sách", cung: [], yeuToThem: "Vị trí Lộc Tồn, Hóa Lộc trên cả lá; chính tinh Tài Bạch", van: [], khongDuoc: "Không hứa số tiền" },
  { id: "TB02", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Kiếm tiền dễ hay khó?", nhanDuoc: "Mức Thuận / Bình / Cần gắng + mốc thay đổi", yBatBuoc: "Mức + 1–2 câu", cung: [], yeuToThem: "Luật chấm Tài Bạch; Tuần/Triệt tại Tài Bạch (mốc tiền vận – hậu vận)", van: ["chuoi"], khongDuoc: "Mức do engine chấm, không để model tự chấm" },
  { id: "TB03", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Tôi có giữ được tiền không, tiền hay hao ở đâu?", nhanDuoc: "Mức giữ tiền + 2–3 chỗ hao cụ thể + cách giữ hợp", yBatBuoc: "Mức + Danh sách", cung: ["Tài Bạch", "Phúc Đức", "Điền Trạch", "Huynh Đệ", "Phu Thê"], yeuToThem: "Không Kiếp, Đại Hao, Tiểu Hao, Phá Quân, Hóa Kỵ; Huynh Đệ (vay mượn); Lộc Tồn ở Phu Thê (bạn đời giữ tiền)", van: [], khongDuoc: "" },
  { id: "TB04", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Tôi có hợp đầu tư không? Kênh nào hợp, kênh nào không?", nhanDuoc: "Có / Không / Có điều kiện + hợp / không hợp + luật kỷ luật", yBatBuoc: "Đáp + Hợp / Không hợp + Luật", cung: ["Tài Bạch", "Điền Trạch", "Phúc Đức", "Mệnh"], yeuToThem: "Thiên Phủ, Vũ Khúc (tích sản) vs Tham Lang, Phá Quân (mạo hiểm); Không Kiếp, Hỏa Linh (đột phát, đột mất); Hóa Kỵ", van: ["dv"], khongDuoc: "Không khuyên mã chứng khoán, không số tiền; luôn kèm câu \"không phải tư vấn tài chính\"" },
  { id: "TB05", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Tôi có hợp hùn hạp, làm ăn chung không?", nhanDuoc: "Hợp / Không + hợp với ai, không hợp với ai", yBatBuoc: "Đáp + Cụ thể", cung: ["Huynh Đệ", "Nô Bộc", "Tài Bạch", "Tử Tức"], yeuToThem: "Tử Tức [một số trường phái xem là cung hợp tác]; sát tinh ở Huynh Đệ, Nô Bộc", van: [], khongDuoc: "" },
  { id: "TB06", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Giai đoạn nào tiền tốt, giai đoạn nào cần giữ?", nhanDuoc: "Bảng các đại vận: Tốt / Bình / Cần giữ", yBatBuoc: "Bảng", cung: ["Tài Bạch", "Điền Trạch"], yeuToThem: "Đại vận có Lộc hoặc đi qua Tài Bạch, Điền Trạch; đại vận gặp Không Kiếp, Hóa Kỵ", van: ["chuoi"], khongDuoc: "" },
  { id: "TB07", loai: "chuyen-sau", chuDe: "tien-bac", cauHoi: "Về sau tôi có của để dành, tài sản lớn không?", nhanDuoc: "Hậu vận tài chính 1–2 câu", yBatBuoc: "Đáp", cung: ["THAN", "Điền Trạch", "Tài Bạch"], yeuToThem: "Cung Thân; đại vận sau 50; Tuần tại Tài Bạch hoặc Điền Trạch", van: ["chuoi"], khongDuoc: "" },
  { id: "TD01", loai: "chuyen-sau", chuDe: "tinh-duyen", cauHoi: "Tôi yêu và gắn bó theo kiểu nào?", nhanDuoc: "Kiểu yêu + điều mình cần ở người kia", yBatBuoc: "Đáp + Cụ thể", cung: ["Mệnh", "Phu Thê", "Phúc Đức"], yeuToThem: "Sao đào hoa tại Mệnh, Phúc Đức", van: [], khongDuoc: "" },
  { id: "TD02", loai: "chuyen-sau", chuDe: "tinh-duyen", cauHoi: "Người bạn đời hợp với tôi là người như thế nào?", nhanDuoc: "Tính cách, hoàn cảnh (tuổi chỉ để tham khảo) + dấu hiệu nhận ra đúng người", yBatBuoc: "Đáp + Cụ thể + Cần biết", cung: [], yeuToThem: "Chính tinh và phụ tinh tại Phu Thê; xung Quan Lộc", van: [], khongDuoc: "Không mô tả ngoại hình như sự thật" },
  { id: "TD03", loai: "chuyen-sau", chuDe: "tinh-duyen", cauHoi: "Duyên đến sớm hay muộn? Giai đoạn, năm nào thuận cho chuyện cưới hỏi?", nhanDuoc: "Sớm / Muộn + giai đoạn + 1–2 năm gợi ý", yBatBuoc: "Đáp + Khi nào", cung: [], yeuToThem: "Tuần/Triệt tại Phu Thê; lưu Hồng Loan, Thiên Hỷ, Đào Hoa", van: ["chuoi", "th3"], khongDuoc: "Không phán ngày cưới; năm luôn ở mức Gợi ý" },
  { id: "TD04", loai: "chuyen-sau", chuDe: "tinh-duyen", cauHoi: "Hôn nhân của tôi thuận hay trắc trở? Dễ vướng gì?", nhanDuoc: "Mức + 2–3 điểm dễ vỡ + điều giữ được", yBatBuoc: "Mức + Danh sách + Cần biết", cung: ["Phu Thê", "Quan Lộc", "Mệnh", "Phúc Đức"], yeuToThem: "Sát tinh, Hóa Kỵ, Cô Thần, Quả Tú tại Phu Thê; xung Quan Lộc", van: ["chuoi"], khongDuoc: "Không phán ly hôn" },
  { id: "TD05", loai: "chuyen-sau", chuDe: "tinh-duyen", cauHoi: "Bạn đời ảnh hưởng thế nào tới sự nghiệp, tiền bạc của tôi?", nhanDuoc: "2 dòng: việc / tiền", yBatBuoc: "2 dòng", cung: ["Phu Thê", "Quan Lộc", "Tài Bạch"], yeuToThem: "Lộc Tồn, Hóa Lộc tại Phu Thê", van: [], khongDuoc: "" },
  { id: "TD06", loai: "chuyen-sau", chuDe: "tinh-duyen", cauHoi: "Tôi có dễ được để ý, có chuyện đào hoa cần lưu ý không?", nhanDuoc: "Mức + lưu ý", yBatBuoc: "Mức + 1–2 câu", cung: ["Mệnh", "Phu Thê", "Phúc Đức", "Thiên Di"], yeuToThem: "Đào Hoa, Hồng Loan, Thiên Riêu, Mộc Dục; Tham Lang, Liêm Trinh", van: [], khongDuoc: "Không phán ngoại tình" },
  { id: "CC01", loai: "chuyen-sau", chuDe: "con-cai", cauHoi: "Duyên con cái của tôi thế nào: sớm hay muộn, thuận hay cần chăm lo?", nhanDuoc: "Sớm / Muộn + thuận / cần chăm lo", yBatBuoc: "Đáp + 1–2 câu", cung: [], yeuToThem: "Tuần/Triệt tại Tử Tức; Thai, Dưỡng", van: ["chuoi"], khongDuoc: "KHÔNG nói số con, con trai hay gái" },
  { id: "CC02", loai: "chuyen-sau", chuDe: "con-cai", cauHoi: "Con tôi có tính cách, tiềm năng ra sao?", nhanDuoc: "Tính cách + điểm mạnh của con", yBatBuoc: "Đáp + Cụ thể", cung: [], yeuToThem: "Chính tinh Tử Tức; không có chính tinh thì mượn Điền Trạch", van: [], khongDuoc: "" },
  { id: "CC03", loai: "chuyen-sau", chuDe: "con-cai", cauHoi: "Quan hệ cha mẹ – con và cách nuôi dạy hợp?", nhanDuoc: "Kiểu quan hệ + cách dạy hợp + điều cần tránh", yBatBuoc: "Đáp + Cụ thể", cung: ["Tử Tức", "Mệnh"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "CC04", loai: "chuyen-sau", chuDe: "con-cai", cauHoi: "Về già tôi có nhờ được con không?", nhanDuoc: "1–2 câu", yBatBuoc: "Đáp", cung: ["Tử Tức", "Điền Trạch"], yeuToThem: "Đại vận cuối", van: ["chuoi"], khongDuoc: "" },
  { id: "GD01", loai: "chuyen-sau", chuDe: "gia-dinh", cauHoi: "Cha mẹ tôi là người thế nào, gia cảnh xuất thân ra sao?", nhanDuoc: "Nét của cha mẹ + gia cảnh", yBatBuoc: "Đáp + Cụ thể", cung: [], yeuToThem: "Chính tinh Phụ Mẫu; Thái Dương (cha), Thái Âm (mẹ) theo độ sáng", van: [], khongDuoc: "Không luận sinh tử cha mẹ" },
  { id: "GD02", loai: "chuyen-sau", chuDe: "gia-dinh", cauHoi: "Tôi có hợp cha mẹ, có được cha mẹ nâng đỡ không?", nhanDuoc: "Mức hợp + kiểu nâng đỡ", yBatBuoc: "Mức + 1–2 câu", cung: [], yeuToThem: "Hóa Khoa, Ân Quang, Thiên Quý tại Phụ Mẫu; Âm Dương thuận lý", van: ["chuoi"], khongDuoc: "" },
  { id: "GD03", loai: "chuyen-sau", chuDe: "gia-dinh", cauHoi: "Gia đình ảnh hưởng tới tôi thế nào (nề nếp, kỳ vọng)?", nhanDuoc: "Điều mang theo từ gia đình", yBatBuoc: "Đáp + Cụ thể", cung: ["Phụ Mẫu", "Phúc Đức", "Mệnh"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "AE01", loai: "chuyen-sau", chuDe: "anh-em", cauHoi: "Anh chị em hòa thuận hay xa cách, có nâng đỡ nhau không?", nhanDuoc: "Mức + kiểu quan hệ", yBatBuoc: "Mức + 1–2 câu", cung: [], yeuToThem: "Chính tinh, sát tinh tại Huynh Đệ", van: [], khongDuoc: "Không nói số anh chị em" },
  { id: "AE02", loai: "chuyen-sau", chuDe: "anh-em", cauHoi: "Có nên hùn tiền, làm ăn với anh em, người thân không?", nhanDuoc: "Có / Không + điều kiện", yBatBuoc: "Đáp + Điều kiện", cung: ["Huynh Đệ", "Tài Bạch"], yeuToThem: "Không Kiếp, Kình Đà tại Huynh Đệ", van: [], khongDuoc: "" },
  { id: "QN01", loai: "chuyen-sau", chuDe: "quy-nhan", cauHoi: "Quý nhân của tôi là ai?", nhanDuoc: "Kiểu người, vị trí, hoàn cảnh gặp quý nhân", yBatBuoc: "Đáp + Cụ thể", cung: [], yeuToThem: "Vị trí Khôi Việt, Tả Hữu, Thiên Quan, Thiên Phúc, Hóa Khoa trên cả lá", van: [], khongDuoc: "" },
  { id: "QN02", loai: "chuyen-sau", chuDe: "quy-nhan", cauHoi: "Bạn bè, cấp dưới, khách hàng: tôi được nhờ hay bị lụy?", nhanDuoc: "Mức + kiểu", yBatBuoc: "Mức + 1–2 câu", cung: [], yeuToThem: "Chính tinh, tứ hóa tại Nô Bộc", van: ["chuoi"], khongDuoc: "" },
  { id: "QN03", loai: "chuyen-sau", chuDe: "quy-nhan", cauHoi: "Kiểu người nào tôi nên giữ khoảng cách?", nhanDuoc: "2–3 kiểu người + dấu hiệu nhận ra", yBatBuoc: "Danh sách + Dấu hiệu", cung: ["Nô Bộc", "Huynh Đệ", "Thiên Di"], yeuToThem: "Sát tinh, Hóa Kỵ tại Nô Bộc, Huynh Đệ", van: [], khongDuoc: "" },
  { id: "PD01", loai: "chuyen-sau", chuDe: "phuc-duc", cauHoi: "Phúc đức gia đình, dòng họ của tôi thế nào?", nhanDuoc: "Phần hưởng sẵn dày hay mỏng + phần tự tạo", yBatBuoc: "Đáp + Cụ thể", cung: [], yeuToThem: "Chính tinh, sát tinh tại Phúc Đức; Thiên Đức, Nguyệt Đức", van: [], khongDuoc: "" },
  { id: "PD02", loai: "chuyen-sau", chuDe: "phuc-duc", cauHoi: "Điều gì làm tôi an, điều gì làm tôi bất an?", nhanDuoc: "2 dòng: an / bất an + cách tự cân bằng", yBatBuoc: "Đáp + Cụ thể", cung: ["Phúc Đức", "Tật Ách", "Mệnh"], yeuToThem: "", van: ["dv"], khongDuoc: "" },
  { id: "PD03", loai: "chuyen-sau", chuDe: "phuc-duc", cauHoi: "Hậu vận của tôi an nhàn hay vất vả?", nhanDuoc: "1–2 câu", yBatBuoc: "Đáp", cung: ["Phúc Đức", "THAN"], yeuToThem: "", van: ["chuoi"], khongDuoc: "KHÔNG luận thọ yểu" },
  { id: "SK01", loai: "chuyen-sau", chuDe: "suc-khoe", cauHoi: "Thể trạng của tôi thế nào, cần để ý gì?", nhanDuoc: "Nền thể trạng + 1–2 xu hướng cần để ý + dấu hiệu tự nhận ra", yBatBuoc: "Đáp + Cụ thể + Độ rõ", cung: [], yeuToThem: "Chính tinh Tật Ách; sát tinh; ngũ hành Mệnh – Cục", van: [], khongDuoc: "KHÔNG chẩn đoán bệnh; bộ phận cơ thể chỉ nói kèm \"theo quan niệm truyền thống, tham khảo\"" },
  { id: "SK02", loai: "chuyen-sau", chuDe: "suc-khoe", cauHoi: "Giai đoạn nào tôi cần giữ sức khỏe hơn?", nhanDuoc: "Các giai đoạn, năm cần giữ", yBatBuoc: "Khi nào", cung: ["Tật Ách"], yeuToThem: "Đại vận, tiểu hạn đi qua Tật Ách hoặc gặp sát tinh, Hóa Kỵ, Bạch Hổ, Thiên Hình", van: ["chuoi", "th3"], khongDuoc: "" },
  { id: "SK03", loai: "chuyen-sau", chuDe: "suc-khoe", cauHoi: "Lối sống, thói quen nào hợp để giữ sức?", nhanDuoc: "3 thói quen cụ thể", yBatBuoc: "Danh sách", cung: ["Tật Ách", "Phúc Đức", "Mệnh"], yeuToThem: "", van: [], khongDuoc: "Không thay lời khuyên y tế" },
  { id: "NC01", loai: "chuyen-sau", chuDe: "nha-cua", cauHoi: "Tôi có dễ có nhà, đất không? Sớm hay muộn?", nhanDuoc: "Mức + mốc giai đoạn", yBatBuoc: "Mức + Khi nào", cung: [], yeuToThem: "Lộc Tồn, Hóa Lộc, Đường Phù; Không Kiếp, Hóa Kỵ tại Điền Trạch", van: ["chuoi"], khongDuoc: "" },
  { id: "NC02", loai: "chuyen-sau", chuDe: "nha-cua", cauHoi: "Tôi được thừa hưởng hay phải tự lập về nhà cửa?", nhanDuoc: "1–2 câu", yBatBuoc: "Đáp", cung: ["Điền Trạch", "Phụ Mẫu"], yeuToThem: "", van: [], khongDuoc: "" },
  { id: "NC03", loai: "chuyen-sau", chuDe: "nha-cua", cauHoi: "Tôi có hay chuyển chỗ ở không? Nơi ở thế nào thì hợp?", nhanDuoc: "Mức + kiểu nơi ở hợp", yBatBuoc: "Đáp + Cụ thể", cung: ["Điền Trạch", "Thiên Di"], yeuToThem: "Thiên Mã, Phá Quân tại Điền Trạch", van: [], khongDuoc: "" },
  { id: "NC04", loai: "chuyen-sau", chuDe: "nha-cua", cauHoi: "Tôi có hợp đầu tư bất động sản không?", nhanDuoc: "Có / Không / Có điều kiện + giai đoạn", yBatBuoc: "Đáp + Điều kiện", cung: ["Điền Trạch", "Tài Bạch"], yeuToThem: "Hóa Kỵ (giấy tờ), Không Kiếp tại Điền Trạch", van: ["dv"], khongDuoc: "Không tư vấn tài chính" },
  { id: "RN01", loai: "chuyen-sau", chuDe: "ra-ngoai", cauHoi: "Ra ngoài xã hội tôi được lợi hay gặp cản trở?", nhanDuoc: "Mức + kiểu", yBatBuoc: "Mức + 1–2 câu", cung: [], yeuToThem: "Chính tinh Thiên Di; Tả Hữu, Khôi Việt", van: [], khongDuoc: "" },
  { id: "RN02", loai: "chuyen-sau", chuDe: "ra-ngoai", cauHoi: "Tôi có hợp đi xa, xuất ngoại, lập nghiệp nơi khác không?", nhanDuoc: "Hợp / Không + kiểu đi", yBatBuoc: "Đáp + Cụ thể", cung: [], yeuToThem: "Thiên Mã, Lộc Mã", van: ["chuoi"], khongDuoc: "" },
  { id: "RN03", loai: "chuyen-sau", chuDe: "ra-ngoai", cauHoi: "Khi đi lại, giao tiếp ngoài xã hội tôi cần lưu ý gì?", nhanDuoc: "1–2 lưu ý", yBatBuoc: "Danh sách", cung: [], yeuToThem: "Lưu Hà, Thiên Hình, sát tinh tại Thiên Di", van: ["th"], khongDuoc: "Không dọa tai nạn" },
  { id: "HV01", loai: "chuyen-sau", chuDe: "hoc-van", cauHoi: "Đường học hành, thi cử, bằng cấp của tôi thế nào?", nhanDuoc: "Mức + giai đoạn học tốt", yBatBuoc: "Mức + Khi nào", cung: ["Quan Lộc", "Phụ Mẫu", "Mệnh"], yeuToThem: "Văn tinh (xem chủ đề)", van: ["chuoi"], khongDuoc: "" },
  { id: "HV02", loai: "chuyen-sau", chuDe: "hoc-van", cauHoi: "Tôi nên học thêm gì để hợp hướng đi?", nhanDuoc: "2–3 hướng học cụ thể", yBatBuoc: "Danh sách", cung: ["Quan Lộc", "Mệnh"], yeuToThem: "Nối với SN01", van: ["dv"], khongDuoc: "" },
  { id: "VH01", loai: "chuyen-sau", chuDe: "van-han", cauHoi: "Bức tranh các giai đoạn 10 năm của đời tôi?", nhanDuoc: "Bảng: mỗi giai đoạn 1 dòng, có mức Thuận / Bình / Cần giữ", yBatBuoc: "Bảng", cung: ["Mệnh"], yeuToThem: "Tam phương mỗi cung vận so với nguyên cục", van: ["chuoi"], khongDuoc: "" },
  { id: "VH02", loai: "chuyen-sau", chuDe: "van-han", cauHoi: "Giai đoạn 10 năm hiện tại của tôi thế nào?", nhanDuoc: "Chủ đề giai đoạn + cơ hội + rủi ro + 4 mảng (việc, tiền, tình, sức) + luật hành động", yBatBuoc: "Đáp + 4 mảng + Luật", cung: ["DV"], yeuToThem: "Tam phương cung vận; sao nguyên cục tại cung vận", van: ["dv"], khongDuoc: "" },
  { id: "VH03", loai: "chuyen-sau", chuDe: "van-han", cauHoi: "Năm nay của tôi thế nào?", nhanDuoc: "Chủ đề năm + 4 mảng, mỗi mảng 1 dòng", yBatBuoc: "Đáp + 4 mảng", cung: ["TH"], yeuToThem: "Lưu Thái Tuế; lưu tứ hóa theo can năm; đối chiếu đại vận", van: ["th", "dv"], khongDuoc: "Năm luôn ở mức Gợi ý" },
  { id: "VH04", loai: "chuyen-sau", chuDe: "van-han", cauHoi: "Năm nay tôi nên làm gì, nên tránh gì?", nhanDuoc: "3 nên + 3 tránh, có điều kiện", yBatBuoc: "Danh sách", cung: ["TH"], yeuToThem: "Như VH03", van: ["th", "dv"], khongDuoc: "" },
  { id: "VH05", loai: "chuyen-sau", chuDe: "van-han", cauHoi: "Tháng nào trong năm thuận, tháng nào cần giữ? [tùy chọn]", nhanDuoc: "Bảng 12 tháng: Thuận / Bình / Cần giữ", yBatBuoc: "Bảng", cung: ["TH"], yeuToThem: "Nguyệt hạn đếm từ tiểu hạn", van: ["th", "nguyet"], khongDuoc: "Chỉ bật khi engine có đủ lưu nguyệt" },
  { id: "VH06", loai: "chuyen-sau", chuDe: "van-han", cauHoi: "Ba năm tới của tôi có xu hướng gì?", nhanDuoc: "Mỗi năm 1 dòng", yBatBuoc: "Bảng", cung: ["TH"], yeuToThem: "Như VH03", van: ["th3", "dv"], khongDuoc: "" },
];
